export type IndustryPage = {
  slug: string;
  name: string;
  badge: string;
  constraint: string;
  because: string;
  proofA: { income: string; desc: string; score: number; band: string };
  proofB: { income: string; desc: string; score: number; band: string };
  outcomes: { title: string; body: string }[];
  prep: string[];
  professionalHref: string;
  professionalLabel: string;
  metaTitle: string;
  metaDesc: string;
};

export const INDUSTRY_PAGES: IndustryPage[] = [
  {
    slug: "consulting",
    name: "Consulting",
    badge: "FOR CONSULTANTS",
    constraint: "You are the product. Know how exposed that makes you.",
    because: "Consulting income feels stable because clients keep coming back. But if your largest client doesn't renew — or you stop delivering — most of your income stops with you. Your score shows how much of your structure is actually protected versus assumed.",
    proofA: { income: "$180K / year", desc: "One anchor client. Project-based work. Nothing on retainer. Income stops when the engagement ends.", score: 29, band: "Limited Stability" },
    proofB: { income: "$180K / year", desc: "Four clients. Two on monthly retainer. Six months of contracted work forward. Income continues without new sales.", score: 71, band: "Established Stability" },
    outcomes: [
      { title: "You find out whether losing your largest client would break your income — or bend it.", body: "If one relationship carries more than half your structure, your score shows it. If your income could absorb the loss, your score shows that too." },
      { title: "You make decisions about rates, hires, and investments knowing your actual stability.", body: "Most consultants make financial decisions based on last quarter. Your score shows the structural position underneath those numbers." },
      { title: "You see exactly what converting one client to a retainer does to your score.", body: "Not a general recommendation. A specific, quantified impact on your structural stability." },
      { title: "You understand how lenders and advisors evaluate your income before you apply.", body: "Self-employed consulting income is the hardest income type to underwrite. Your score gives you a number before anyone else puts one on you." },
      { title: "Progress becomes visible as you build a more resilient structure.", body: "Add a retainer. Reduce concentration. Add a second anchor client. Your score reflects each structural change." },
    ],
    prep: [
      "Know what % of your income comes from your single largest client",
      "Know whether your current work is contracted, retainer, or project-by-project",
      "Think about what your income looks like in month 2 if you sign nothing new today",
    ],
    professionalHref: "/advisors",
    professionalLabel: "Are you a financial advisor working with consultants?",
    metaTitle: "Income Stability Score for Consultants — RunPayway™",
    metaDesc: "Know how exposed your consulting income actually is. RunPayway™ scores your income structure in under two minutes — concentration risk, recurring income, and what to fix first.",
  },
  {
    slug: "real-estate",
    name: "Real Estate",
    badge: "FOR REAL ESTATE PROFESSIONALS",
    constraint: "Nothing is contractually yours until it closes.",
    because: "Real estate income depends on deals that haven't happened yet. One delayed transaction, one lost listing, and a quarter of annual earnings can disappear. Your score shows how much of your pipeline is actually secured versus assumed.",
    proofA: { income: "$160K / year", desc: "Five deals in pipeline. None under contract. Two verbal commitments. Income entirely depends on all five closing on time.", score: 31, band: "Limited Stability" },
    proofB: { income: "$140K / year", desc: "Three deals under signed contract. Consistent referral network generating repeat business. Two years of stable closing history.", score: 68, band: "Established Stability" },
    outcomes: [
      { title: "You know exactly how much of your pipeline is secured versus assumed.", body: "Verbal agreements and active listings are not income. Your score reflects only what is structurally in place." },
      { title: "You make financing decisions knowing whether your income structure can support them.", body: "Buying a home, taking on a lease, or making an investment requires knowing your income's actual floor — not your best recent quarter." },
      { title: "You see what building a referral base or recurring channel does to your structural score.", body: "Property management income, referral networks, and repeat clients change your score. Your assessment shows by how much." },
      { title: "You understand how mortgage lenders evaluate your income — before you apply.", body: "Self-employed real estate income is among the hardest to underwrite. Your score shows you what they see before you sit across the table." },
      { title: "You track how your structure changes as you close, contract, and build recurring income.", body: "Each structural improvement — signed contracts, a retained client, a new income source — moves your score. Progress is measurable." },
    ],
    prep: [
      "Know how many deals are under signed contract vs. verbal pipeline right now",
      "Know roughly what % of last year's income came from your top 1–2 closings",
      "Think about whether you have any income that continues between transactions",
    ],
    professionalHref: "/lenders",
    professionalLabel: "Are you a lender working with real estate professionals?",
    metaTitle: "Income Stability Score for Real Estate Professionals — RunPayway™",
    metaDesc: "Pipeline income isn't guaranteed income. RunPayway™ scores your real estate income structure in under two minutes — what's secured, what's at risk, and what to fix first.",
  },
  {
    slug: "sales-brokerage",
    name: "Sales & Brokerage",
    badge: "FOR SALES PROFESSIONALS",
    constraint: "Last quarter's earnings don't carry forward.",
    because: "Commission income resets every cycle. Strong quarters mask the fact that nothing is structurally guaranteed next month. Your score separates what has a floor from what starts at zero every 30 days.",
    proofA: { income: "$140K / year", desc: "100% commission. Single product line. One territory. Income requires continuous closing every month to maintain.", score: 36, band: "Developing Stability" },
    proofB: { income: "$120K / year", desc: "Base plus commission. Multiple product lines. Renewal book generating 40% of income automatically each month.", score: 67, band: "Established Stability" },
    outcomes: [
      { title: "You find out how much of your income actually resets to zero each month.", body: "Commission income feels continuous when things are going well. Your score shows what the structural floor actually is." },
      { title: "You make financial commitments knowing what your income looks like when deals don't close.", body: "Mortgages, leases, and long-term commitments need to be supported by structural income — not strong months." },
      { title: "You see what adding a renewal base or recurring component does to your score.", body: "The shift from pure commission to a base-plus-renewal structure is the single biggest structural change most sales professionals can make." },
      { title: "You understand how lenders view commission income before you apply.", body: "Commission earners are underwritten differently. Your score shows your structural position before any lender evaluates it." },
      { title: "You track your structural stability as your income mix evolves.", body: "As your renewal base grows, your base adjusts, or you add product lines, your score reflects the change." },
    ],
    prep: [
      "Know what % of this quarter's earnings will carry forward automatically",
      "Know how many separate commission sources your income comes from",
      "Think about what your income is in a month where no deals close",
    ],
    professionalHref: "/advisors",
    professionalLabel: "Are you a financial advisor working with sales professionals?",
    metaTitle: "Income Stability Score for Sales Professionals — RunPayway™",
    metaDesc: "Commission income resets every cycle. RunPayway™ scores your income structure in under two minutes — how much has a floor, how much resets, and what to fix first.",
  },
  {
    slug: "freelance-creative",
    name: "Freelance & Creative",
    badge: "FOR FREELANCERS & CREATIVES",
    constraint: "Every month starts at zero unless you've built a floor.",
    because: "Freelance income can look strong in active months and disappear between projects. Without retainers or recurring clients, you re-earn your entire income every 30 days. Your score shows how much of your structure actually has a floor.",
    proofA: { income: "$90K / year", desc: "Project-based work only. No retainers. Income stops completely between engagements. Strong months hide the structural gap.", score: 27, band: "Limited Stability" },
    proofB: { income: "$85K / year", desc: "Two monthly retainer clients. One licensing agreement. 50% of income continues regardless of active project work.", score: 72, band: "Established Stability" },
    outcomes: [
      { title: "You find out how much of your income would survive a month with no new projects.", body: "If your structure has no floor, your score shows it. If retainers or recurring clients create one, your score quantifies it." },
      { title: "You make financial decisions based on your structural floor — not your best month.", body: "Housing, equipment, insurance, and long-term commitments need to be supported by what your income does consistently, not occasionally." },
      { title: "You see exactly what converting one client to a retainer does to your score.", body: "The structural impact of one retainer agreement often surprises people. Your assessment shows the specific number." },
      { title: "You understand how lenders and advisors evaluate irregular income.", body: "Freelance income is among the hardest for financial institutions to assess. Your score gives you a number before anyone else defines it for you." },
      { title: "You track progress as you build recurring income into your structure.", body: "Each retainer added, each licensing deal signed, each recurring client acquired moves your score. Change is measurable." },
    ],
    prep: [
      "Know how many clients are actively paying you right now",
      "Know whether any of your income repeats without you re-selling it",
      "Think about what your income would be if you signed nothing new for 30 days",
    ],
    professionalHref: "/advisors",
    professionalLabel: "Are you a financial advisor working with freelancers?",
    metaTitle: "Income Stability Score for Freelancers — RunPayway™",
    metaDesc: "Project income resets every month. RunPayway™ scores your freelance income structure in under two minutes — your floor, your risk, and what to fix first.",
  },
  {
    slug: "construction-trades",
    name: "Construction & Trades",
    badge: "FOR CONSTRUCTION & TRADES PROFESSIONALS",
    constraint: "The next job isn't signed. And your fixed costs don't know that.",
    because: "Construction income is real while a project runs. When it ends, the next one might be a verbal agreement, a prospect, or nothing yet. Your score shows how much structural buffer sits between your current project and your next signed commitment.",
    proofA: { income: "$120K / year", desc: "One major project running. Nothing signed next. Two prospects in conversation. Income depends on handshakes converting to contracts.", score: 34, band: "Developing Stability" },
    proofB: { income: "$110K / year", desc: "Current project running six more months. Two signed contracts starting consecutively. 60% repeat client base generating reliable backlog.", score: 69, band: "Established Stability" },
    outcomes: [
      { title: "You find out how much signed backlog actually exists versus what's assumed.", body: "Verbal agreements, ongoing conversations, and repeat clients who haven't committed yet are not income. Your score reflects what's actually signed." },
      { title: "You make financial decisions knowing what your income looks like between projects.", body: "Equipment purchases, hiring, and long-term commitments need to be supported by contracted income — not pipeline optimism." },
      { title: "You see what building a repeat client base does to your structural score.", body: "Repeat customers who generate predictable backlog change the structure of your income. Your assessment shows how much." },
      { title: "You understand how lenders evaluate construction and trades income.", body: "Project-based income is difficult to underwrite. Your score gives you a structural picture before any lender forms one." },
      { title: "You track your structural stability as your backlog and client base evolves.", body: "As signed work increases and your repeat client base grows, your score reflects the improvement." },
    ],
    prep: [
      "Know how many months of signed work you currently have in backlog",
      "Know what % of your jobs come from repeat vs. new customers",
      "Think about whether your income stops completely between projects",
    ],
    professionalHref: "/lenders",
    professionalLabel: "Are you a lender working with construction or trades professionals?",
    metaTitle: "Income Stability Score for Construction & Trades — RunPayway™",
    metaDesc: "Project income has gaps. RunPayway™ scores your construction income structure in under two minutes — your backlog, your risk, and what to fix first.",
  },
  {
    slug: "media-entertainment",
    name: "Media & Entertainment",
    badge: "FOR MEDIA & ENTERTAINMENT PROFESSIONALS",
    constraint: "Between projects, income isn't low. It's zero.",
    because: "Strong projects create strong months. But the calendar between them isn't slow — it's structurally empty. Media and entertainment income has no carry between engagements. Your score shows what exists between projects, and what doesn't.",
    proofA: { income: "$95K / year", desc: "Three strong project months across the year. Nine months between engagements. No residual income. No structural carry.", score: 25, band: "Limited Stability" },
    proofB: { income: "$80K / year", desc: "Two recurring clients on retainer. Licensing income from prior work. Active project income supplemented by residuals.", score: 52, band: "Developing Stability" },
    outcomes: [
      { title: "You find out how much of your income structure exists between active engagements.", body: "If the answer is nothing, your score reflects that clearly. If licensing, residuals, or retainers create a floor, your score quantifies it." },
      { title: "You make financial decisions knowing your structural floor — not your project months.", body: "Long-term commitments need to be supported by what your income does in slow months, not what it does during a strong project." },
      { title: "You see what licensing past work or building a retainer relationship does to your score.", body: "Income that continues without active work is the structural lever most media professionals have access to but haven't pulled." },
      { title: "You understand how lenders and advisors evaluate irregular creative income.", body: "Entertainment income is among the least understood income types for financial institutions. Your score gives you a number before they define one." },
      { title: "You track progress as you build income that continues between projects.", body: "Each licensing deal, each recurring client, each residual stream changes your structural score." },
    ],
    prep: [
      "Know how many months your current projects or contracts run",
      "Know whether you have any income that continues between active engagements",
      "Think about what your income looks like in a month with no active project",
    ],
    professionalHref: "/advisors",
    professionalLabel: "Are you a financial advisor working with media or entertainment professionals?",
    metaTitle: "Income Stability Score for Media & Entertainment Professionals — RunPayway™",
    metaDesc: "Project gaps mean income gaps. RunPayway™ scores your income structure in under two minutes — what exists between engagements, what doesn't, and what to build first.",
  },
  {
    slug: "insurance",
    name: "Insurance",
    badge: "FOR INSURANCE PROFESSIONALS",
    constraint: "New production hides what's happening underneath.",
    because: "Strong new business quarters feel like growth. But if your renewal book is eroding beneath the surface, your total income structure is compounding backwards. Your score separates what's actually recurring from what you're having to re-earn.",
    proofA: { income: "$130K / year", desc: "Strong new production every quarter. Renewal retention at 72% and declining year over year. New business masks the structural erosion beneath.", score: 41, band: "Developing Stability" },
    proofB: { income: "$115K / year", desc: "Renewal retention at 91%. Recurring book covers 65% of income automatically. New production builds on a stable, compounding floor.", score: 74, band: "Established Stability" },
    outcomes: [
      { title: "You find out how much of your income is actually recurring versus re-earned.", body: "Renewals that stay are recurring income. Renewals that leave are re-earn. Your score separates the two." },
      { title: "You make financial decisions knowing your structural floor under your production numbers.", body: "Base income from a healthy renewal book is a different financial foundation than production-dependent income alone." },
      { title: "You see what improving renewal retention does to your long-term structural score.", body: "A 10-point improvement in renewal retention often has more structural impact than a 20% increase in new production." },
      { title: "You understand how advisors and lenders evaluate commission-based insurance income.", body: "Insurance professional income is complex to evaluate from the outside. Your score gives you a clear structural picture first." },
      { title: "You track your book's structural health as renewal retention and new production both change.", body: "Your score reflects the underlying structure — not just the top-line production numbers." },
    ],
    prep: [
      "Know what % of your income is renewals vs. new production",
      "Know whether your renewal book is growing, flat, or declining",
      "Think about how much your income would drop if new sales stopped for 90 days",
    ],
    professionalHref: "/advisors",
    professionalLabel: "Are you a financial advisor working with insurance professionals?",
    metaTitle: "Income Stability Score for Insurance Professionals — RunPayway™",
    metaDesc: "New production can hide renewal erosion. RunPayway™ scores your insurance income structure in under two minutes — what's recurring, what's at risk, and what to strengthen first.",
  },
  {
    slug: "legal-services",
    name: "Legal Services",
    badge: "FOR LEGAL PROFESSIONALS",
    constraint: "Three matters carry your practice. When one concludes, the gap arrives all at once.",
    because: "Legal billings are concentrated in ways that aren't visible until a major matter ends. Your top matters likely carry 60–70% of your practice. Your score shows how structurally dependent your income is on a small number of client relationships.",
    proofA: { income: "$220K / year", desc: "Two major matters. Both approaching conclusion. No retainer agreements. A significant income gap is arriving within the next quarter.", score: 38, band: "Developing Stability" },
    proofB: { income: "$190K / year", desc: "Seven active matters. Three ongoing retainer agreements. No single matter represents more than 25% of annual billings.", score: 73, band: "Established Stability" },
    outcomes: [
      { title: "You find out how concentrated your practice income actually is.", body: "If two matters carry 60% of your billings, your score reflects that concentration. If you're well-diversified across matters, your score reflects that too." },
      { title: "You make financial decisions knowing what your income looks like when major matters conclude.", body: "The gap after a major matter ends is predictable. Your score shows its structural severity before it arrives." },
      { title: "You see what building retainer relationships does to your practice's income structure.", body: "Retainer income changes the structural profile of a legal practice more than almost any other single change." },
      { title: "You understand how lenders and financial advisors evaluate law firm income.", body: "Legal practice income is among the most complex income structures to evaluate. Your score gives you a clear structural picture first." },
      { title: "You track how your practice's structural stability changes as matters open, close, and evolve.", body: "Your score reflects the current structural state of your practice — updated as your matter mix changes." },
    ],
    prep: [
      "Know how many active matters you currently have",
      "Know what % of your billings come from your top 2–3 matters",
      "Think about whether any of your income is on retainer vs. matter-by-matter",
    ],
    professionalHref: "/advisors",
    professionalLabel: "Are you a financial advisor working with legal professionals?",
    metaTitle: "Income Stability Score for Legal Professionals — RunPayway™",
    metaDesc: "Matter concentration creates hidden risk. RunPayway™ scores your legal practice income structure in under two minutes — concentration, recurring income, and what to address first.",
  },
  {
    slug: "technology",
    name: "Technology",
    badge: "FOR TECHNOLOGY PROFESSIONALS",
    constraint: "One employer. One system. One decision away from a total reset.",
    because: "Technology compensation feels stable because the system around it is stable. But single-employer dependence, unvested equity, and variable comp components mean your actual structure is more exposed than your base salary suggests. Your score shows what's protected and what isn't.",
    proofA: { income: "$185K / year", desc: "Single employer. 40% of total comp in unvested equity. No outside income. Entire compensation disappears with one organizational decision.", score: 43, band: "Developing Stability" },
    proofB: { income: "$160K / year", desc: "Primary employer plus consulting income. Equity substantially vested. No single income source above 70% of total compensation.", score: 71, band: "Established Stability" },
    outcomes: [
      { title: "You find out how much of your total compensation is structurally protected versus assumed.", body: "Base salary, unvested equity, and variable bonuses have completely different structural profiles. Your score evaluates all three." },
      { title: "You make financial decisions knowing your income's real floor — not just your base salary.", body: "If 40% of your compensation is unvested equity, your actual structural floor is significantly lower than your offer letter suggests." },
      { title: "You see what adding an outside income source does to your structural score.", body: "Consulting income, a side business, or any income outside your primary employer changes your concentration risk meaningfully." },
      { title: "You understand how lenders and advisors evaluate technology compensation.", body: "RSUs, bonuses, and variable tech comp are complex to underwrite. Your score gives you a structural picture before any external evaluation." },
      { title: "You track your structural stability as your equity vests, income sources change, and comp evolves.", body: "Each structural change — vesting, a new income source, a comp restructure — moves your score." },
    ],
    prep: [
      "Know what % of your total compensation is variable — bonus, equity, or commissions",
      "Know how many income sources you have outside your primary employer",
      "Think about what your income looks like if your role was eliminated today",
    ],
    professionalHref: "/advisors",
    professionalLabel: "Are you a financial advisor working with technology professionals?",
    metaTitle: "Income Stability Score for Technology Professionals — RunPayway™",
    metaDesc: "Tech compensation is more complex than your offer letter shows. RunPayway™ scores your income structure in under two minutes — equity exposure, concentration risk, and what to address first.",
  },
  {
    slug: "finance-banking",
    name: "Finance & Banking",
    badge: "FOR FINANCE & BANKING PROFESSIONALS",
    constraint: "Your base creates a floor. Your bonus is where you actually live — and it can vanish in one cycle.",
    because: "Finance compensation looks stable until you separate fixed from variable. The bonus, production credit, or carried interest is where real earnings happen — and that part can disappear in a single market or performance cycle. Your score shows how much of your total income is structurally protected.",
    proofA: { income: "$250K / year", desc: "Base $90K. Bonus $160K, entirely market and performance dependent. One bad year eliminates 64% of total compensation.", score: 39, band: "Developing Stability" },
    proofB: { income: "$210K / year", desc: "Base $130K. Bonus structured on retained AUM fees rather than new production. Variable portion tied to recurring client relationships.", score: 67, band: "Established Stability" },
    outcomes: [
      { title: "You find out how much of your compensation is structurally protected versus market-dependent.", body: "Base and variable have entirely different structural profiles. Your score evaluates both and shows the real picture." },
      { title: "You make financial decisions knowing your structural floor — not your best compensation year.", body: "Mortgages, investments, and long-term commitments need to be supported by income that continues in a down cycle, not just peak years." },
      { title: "You see what shifting variable comp from production-based to retention-based does to your score.", body: "AUM-based fees tied to retained clients are structurally different from bonuses tied to new production. Your score quantifies the difference." },
      { title: "You understand how your compensation structure is evaluated from the outside.", body: "High-earning finance professionals are often surprised how lenders and advisors view variable-heavy compensation. Your score shows that picture first." },
      { title: "You track structural changes as your base adjusts, variable composition evolves, and income sources diversify.", body: "Each structural improvement — a higher base, more recurring variable income, outside sources — changes your score." },
    ],
    prep: [
      "Know what % of your annual compensation is variable vs. fixed base",
      "Know whether your base salary alone would cover your financial obligations",
      "Think about how tied your income is to market conditions or deal flow",
    ],
    professionalHref: "/advisors",
    professionalLabel: "Are you a financial advisor working with finance and banking professionals?",
    metaTitle: "Income Stability Score for Finance & Banking Professionals — RunPayway™",
    metaDesc: "Variable compensation creates hidden structural risk. RunPayway™ scores your income structure in under two minutes — fixed vs. variable, concentration, and what to strengthen first.",
  },
  {
    slug: "healthcare",
    name: "Healthcare",
    badge: "FOR HEALTHCARE PROFESSIONALS",
    constraint: "One institution. No alternative. One restructuring away from a total reset.",
    because: "Healthcare income from a single institution feels stable until the institution changes models, consolidates, or restructures. Your score shows how dependent your income is on one system continuing exactly as it is — and what your structure looks like if it doesn't.",
    proofA: { income: "$175K / year", desc: "Single hospital system. All compensation from one employer. No private practice. No secondary income stream of any kind.", score: 44, band: "Developing Stability" },
    proofB: { income: "$165K / year", desc: "Primary institution plus part-time private practice. Income from two systems. No single employer represents more than 70% of total income.", score: 70, band: "Established Stability" },
    outcomes: [
      { title: "You find out how exposed your income is to a single institutional decision.", body: "If one hospital system accounts for all your income, your score reflects that concentration clearly." },
      { title: "You make financial decisions knowing your structural floor — not your employment contract.", body: "An employment contract is not the same as income security. Your score shows what actually supports your financial decisions." },
      { title: "You see what adding a private practice or secondary income stream does to your structural score.", body: "Even a small outside income source meaningfully changes your concentration risk. Your assessment quantifies the impact." },
      { title: "You understand how lenders and advisors evaluate healthcare professional income.", body: "High-earning healthcare professionals are often surprised how lenders view single-institution income. Your score shows that picture first." },
      { title: "You track structural changes as your income sources and employment situation evolves.", body: "Each structural change — a new position, a private practice addition, a side income — moves your score." },
    ],
    prep: [
      "Know whether your income comes from one institution or multiple sources",
      "Know what your income would look like if your primary employer restructured",
      "Think about whether any of your income continues when you're not actively working",
    ],
    professionalHref: "/advisors",
    professionalLabel: "Are you a financial advisor working with healthcare professionals?",
    metaTitle: "Income Stability Score for Healthcare Professionals — RunPayway™",
    metaDesc: "Single-institution income has hidden concentration risk. RunPayway™ scores your healthcare income structure in under two minutes — exposure, alternatives, and what to address first.",
  },
  {
    slug: "retail-ecommerce",
    name: "Retail & E-Commerce",
    badge: "FOR RETAIL & E-COMMERCE PROFESSIONALS",
    constraint: "Revenue is not income. The gap between them is your structural risk.",
    because: "Retail and e-commerce revenue can look strong until you account for inventory costs, returns, platform fees, and seasonal swings. Your score is based on the income that actually reaches you — and how stable that structure is across months and product lines.",
    proofA: { income: "$110K / year", desc: "Single product line. One sales platform. Revenue highly seasonal. Margins compressed by platform fees, returns, and inventory costs.", score: 30, band: "Limited Stability" },
    proofB: { income: "$95K / year", desc: "Multiple product categories. Two sales channels. Subscription product generating 35% of monthly revenue automatically.", score: 68, band: "Established Stability" },
    outcomes: [
      { title: "You find out whether your revenue concentration in one product or platform is a structural risk.", body: "Single-platform dependence and single-product concentration are the two structural risks most retail businesses carry. Your score shows which applies to you." },
      { title: "You make financial decisions knowing your structural income — not your best revenue month.", body: "Business investments, leases, and hires need to be supported by consistent income, not seasonal peaks." },
      { title: "You see what adding a subscription or recurring revenue component does to your score.", body: "Recurring revenue changes the structural profile of a retail or e-commerce business more than almost any other single change." },
      { title: "You understand how lenders evaluate business income for retail and e-commerce operators.", body: "Revenue is not income, and lenders know it. Your score shows your actual structural position before any external evaluation." },
      { title: "You track structural changes as your product mix, channels, and revenue composition evolve.", body: "Each structural improvement — a new channel, a subscription product, a diversified product line — moves your score." },
    ],
    prep: [
      "Know how much your monthly revenue varies from your best to your slowest month",
      "Know whether you rely on one core product or have multiple lines",
      "Think about what % of your revenue comes from returning vs. new customers",
    ],
    professionalHref: "/advisors",
    professionalLabel: "Are you a financial advisor working with retail or e-commerce business owners?",
    metaTitle: "Income Stability Score for Retail & E-Commerce — RunPayway™",
    metaDesc: "Revenue and income are not the same. RunPayway™ scores your retail income structure in under two minutes — concentration, recurring revenue, and what to strengthen first.",
  },
  {
    slug: "hospitality",
    name: "Hospitality & Food Service",
    badge: "FOR HOSPITALITY & FOOD SERVICE PROFESSIONALS",
    constraint: "Your revenue is a daily vote that customers can stop casting without notice.",
    because: "Hospitality income is entirely demand-dependent. One slow season, one shift in foot traffic, one bad review — and income can drop without structural warning. Your score shows how much buffer exists between daily demand and your income floor.",
    proofA: { income: "$80K / year", desc: "Foot traffic only. No contracted events. No alternative channel. One location. Revenue follows daily customer decisions with no structural floor.", score: 26, band: "Limited Stability" },
    proofB: { income: "$75K / year", desc: "Walk-in business plus contracted private events. Catering agreements covering 30% of annual revenue. Two locations reduce single-point risk.", score: 54, band: "Developing Stability" },
    outcomes: [
      { title: "You find out how exposed your income is to a shift in daily demand.", body: "If your income has no floor below foot traffic, your score shows it clearly. Contracted revenue changes the picture." },
      { title: "You make financial decisions knowing what your income looks like in your slowest month.", body: "Leases, equipment, staff — these commitments need to be supported by income in slow months, not strong ones." },
      { title: "You see what contracted events or a catering line does to your structural score.", body: "Contracted revenue is structurally different from walk-in revenue. Your assessment shows the specific score impact." },
      { title: "You understand how lenders evaluate hospitality business income.", body: "Variable, seasonal income is among the most difficult to underwrite. Your score gives you a structural picture before any lender forms one." },
      { title: "You track structural changes as you add contracted revenue, new locations, and alternative channels.", body: "Each structural addition — an event contract, a second location, a delivery channel — changes your score." },
    ],
    prep: [
      "Know what your income looks like in your slowest month of the year",
      "Know how much of your revenue is tied to foot traffic vs. contracted events",
      "Think about how quickly your income would change if demand shifted",
    ],
    professionalHref: "/advisors",
    professionalLabel: "Are you a financial advisor working with hospitality or food service business owners?",
    metaTitle: "Income Stability Score for Hospitality & Food Service — RunPayway™",
    metaDesc: "Demand-dependent income has a structural floor problem. RunPayway™ scores your hospitality income structure in under two minutes — seasonal exposure, contracted revenue, and what to build first.",
  },
  {
    slug: "transportation-logistics",
    name: "Transportation & Logistics",
    badge: "FOR TRANSPORTATION & LOGISTICS PROFESSIONALS",
    constraint: "An idle route earns nothing. Utilization is your entire income structure.",
    because: "Transportation income depends on constant movement and active clients. When a route pauses, a client leaves, or a truck is idle, income stops immediately and fixed costs continue. Your score shows how much of your revenue is contractually secured versus dependent on utilization staying constant.",
    proofA: { income: "$115K / year", desc: "Two major clients. No contracts. Both operating on rate-and-route arrangements that can pause with 30 days notice.", score: 35, band: "Developing Stability" },
    proofB: { income: "$100K / year", desc: "Four clients. Two on annual contracted rates. 60% of revenue locked across signed agreements for the next 10 months.", score: 66, band: "Established Stability" },
    outcomes: [
      { title: "You find out how much of your revenue is contractually secured vs. dependent on utilization.", body: "The difference between a rate agreement and a signed contract is the difference between assumed income and structural income." },
      { title: "You make financial decisions knowing what your income looks like when a major client pauses.", body: "Equipment financing, facility leases, and staff costs need to be supported by income that has a contractual floor." },
      { title: "You see what converting major clients to contracted rates does to your structural score.", body: "Annual contracts versus rate agreements are the single biggest structural lever in transportation income." },
      { title: "You understand how lenders evaluate transportation and logistics business income.", body: "Utilization-dependent income is difficult to underwrite. Your score gives you a structural position before any external evaluation." },
      { title: "You track structural changes as your client base, contracts, and route mix evolve.", body: "Each new signed contract, each additional client, each diversified route changes your structural score." },
    ],
    prep: [
      "Know how many active clients or contracts you currently have",
      "Know what happens to your income if your largest route or client pauses",
      "Think about whether your income is consistent or heavily tied to utilization",
    ],
    professionalHref: "/advisors",
    professionalLabel: "Are you a financial advisor working with transportation or logistics business owners?",
    metaTitle: "Income Stability Score for Transportation & Logistics — RunPayway™",
    metaDesc: "Utilization-dependent income has structural gaps. RunPayway™ scores your transportation income structure in under two minutes — contracted revenue, client concentration, and what to fix first.",
  },
  {
    slug: "manufacturing",
    name: "Manufacturing",
    badge: "FOR MANUFACTURING PROFESSIONALS",
    constraint: "Your largest buyer likely carries 40% of your output. Their decision is your risk.",
    because: "Manufacturing income is stable until your largest buyer renegotiates, delays, or leaves. When revenue is concentrated in one or two buyers, your fixed costs don't adjust with the change. Your score shows how concentrated your output is and how exposed that makes your income.",
    proofA: { income: "$200K / year", desc: "One buyer represents 65% of output. No long-term purchase agreements. Annual negotiation determines pricing and volume each year.", score: 37, band: "Developing Stability" },
    proofB: { income: "$175K / year", desc: "Four buyers. Largest represents 28% of output. Two multi-year supply agreements providing revenue visibility 18 months forward.", score: 69, band: "Established Stability" },
    outcomes: [
      { title: "You find out how concentrated your output and revenue actually are.", body: "If one buyer carries more than 40% of your output, your score reflects that exposure. Diversification changes the picture." },
      { title: "You make capital and staffing decisions knowing your structural revenue floor.", body: "Equipment investment, facility expansion, and hiring need to be supported by contracted revenue, not assumed buyer relationships." },
      { title: "You see what multi-year supply agreements do to your structural score.", body: "Contracted purchase agreements are structurally different from ongoing buyer relationships. Your assessment shows the specific impact." },
      { title: "You understand how lenders evaluate manufacturing business income.", body: "Buyer concentration and contract duration are the two factors lenders focus on for manufacturing operations. Your score shows both." },
      { title: "You track structural changes as your buyer mix, contract coverage, and revenue diversification evolve.", body: "Each new buyer, each supply agreement signed, each reduction in top-buyer concentration moves your score." },
    ],
    prep: [
      "Know what % of your output goes to your single largest buyer",
      "Know whether your current contracts are signed agreements or ongoing relationships",
      "Think about how your fixed costs compare to your income in a slow month",
    ],
    professionalHref: "/advisors",
    professionalLabel: "Are you a financial advisor working with manufacturing business owners?",
    metaTitle: "Income Stability Score for Manufacturing — RunPayway™",
    metaDesc: "Buyer concentration is the hidden risk in manufacturing income. RunPayway™ scores your income structure in under two minutes — buyer exposure, contract coverage, and what to address first.",
  },
  {
    slug: "education",
    name: "Education",
    badge: "FOR EDUCATION PROFESSIONALS",
    constraint: "Your income is stable because the structure caps it. Stability has a ceiling.",
    because: "Education income is among the most structurally predictable — until the institution changes, funding shifts, or you want more than the structure allows. Your score shows exactly where your stability sits, what the ceiling is, and what additional income sources would change your picture.",
    proofA: { income: "$68K / year", desc: "Single institution. All income from one employer. Predictable but fully capped. Growth requires changing the structure entirely.", score: 62, band: "Established Stability" },
    proofB: { income: "$92K / year", desc: "Primary institution plus two adjunct positions plus online course licensing income. Multiple income sources, meaningful floor above base salary.", score: 81, band: "High Stability" },
    outcomes: [
      { title: "You find out where your income stability actually sits on a 0–100 scale.", body: "Single-institution education income is often more stable than it feels — but also more capped. Your score shows both." },
      { title: "You make financial decisions knowing your institutional floor and what lies above it.", body: "The gap between your current structure and what outside income sources could provide is visible in your score." },
      { title: "You see what adjunct positions, course licensing, or outside consulting do to your income picture.", body: "Additional income sources don't just add revenue — they change your structural profile. Your assessment shows how." },
      { title: "You understand how lenders and advisors evaluate educator income.", body: "Education income is stable but concentrated. Your score shows the structural picture clearly before any external evaluation." },
      { title: "You track how your structure changes as you build income sources outside your primary institution.", body: "Each additional source — a course, an adjunct position, a consulting engagement — changes your structural score." },
    ],
    prep: [
      "Know whether your income comes from one institution or multiple sources",
      "Know what your income would be if your primary position ended today",
      "Think about whether you have any income outside your primary teaching or instruction role",
    ],
    professionalHref: "/advisors",
    professionalLabel: "Are you a financial advisor working with education professionals?",
    metaTitle: "Income Stability Score for Education Professionals — RunPayway™",
    metaDesc: "Stable doesn't mean uncapped. RunPayway™ scores your education income structure in under two minutes — institutional concentration, outside income, and what your picture could look like.",
  },
  {
    slug: "nonprofit",
    name: "Nonprofit & Public Sector",
    badge: "FOR NONPROFIT & PUBLIC SECTOR PROFESSIONALS",
    constraint: "Your position exists because funding was renewed. The next cycle isn't guaranteed.",
    because: "Nonprofit and public sector income is only as secure as the budget or grant cycle that funds it. When cycles turn, positions disappear regardless of performance or tenure. Your score shows how structurally dependent your income is on funding decisions outside your control.",
    proofA: { income: "$72K / year", desc: "Grant-funded position. One-year grant. Renewal pending. No alternative income source. Position disappears if the grant doesn't renew.", score: 32, band: "Developing Stability" },
    proofB: { income: "$78K / year", desc: "Base salary from operating budget. Two additional grant-funded responsibilities. No single funding source above 55% of total income.", score: 65, band: "Established Stability" },
    outcomes: [
      { title: "You find out how dependent your income is on a single funding cycle renewing.", body: "If one grant or budget line carries most of your income, your score reflects that structural dependency." },
      { title: "You make financial decisions knowing what your income looks like if funding changes.", body: "Long-term personal financial commitments need to account for the funding cycle your income depends on." },
      { title: "You see what diversifying across multiple funding sources does to your structural score.", body: "Multiple funding streams, even within the same organization, change your structural exposure meaningfully." },
      { title: "You understand how lenders and advisors evaluate nonprofit and public sector income.", body: "Funding-dependent income is often misunderstood by financial institutions. Your score gives you a clear picture first." },
      { title: "You track structural changes as your funding composition and employment situation evolves.", body: "Changes in grant mix, budget allocation, and outside income all move your score." },
    ],
    prep: [
      "Know whether your position is grant-funded, budget-funded, or both",
      "Know when your current funding cycle ends",
      "Think about whether your income could continue if the primary funding source changed",
    ],
    professionalHref: "/advisors",
    professionalLabel: "Are you a financial advisor working with nonprofit or public sector professionals?",
    metaTitle: "Income Stability Score for Nonprofit & Public Sector Professionals — RunPayway™",
    metaDesc: "Funding cycles create structural risk. RunPayway™ scores your income structure in under two minutes — funding dependency, income sources, and what to understand before the next cycle.",
  },
  {
    slug: "agriculture",
    name: "Agriculture",
    badge: "FOR AGRICULTURE PROFESSIONALS",
    constraint: "You can't control the two things that matter most: weather and price.",
    because: "Agricultural income is structurally exposed to forces entirely outside your control. A single bad season, a commodity price drop, or the loss of one buyer can erase a year of work. Your score shows how much structural protection exists between your operation and those forces.",
    proofA: { income: "$95K / year", desc: "Single crop. Open market pricing. No forward contracts. One primary buyer. Income entirely dependent on season, price, and that buyer relationship continuing.", score: 24, band: "Limited Stability" },
    proofB: { income: "$88K / year", desc: "Two crop types. 40% of output sold under forward contracts. Direct-to-consumer channel providing a second revenue stream.", score: 53, band: "Developing Stability" },
    outcomes: [
      { title: "You find out how much structural protection exists between market forces and your income.", body: "Forward contracts, multiple buyers, and diversified crops each change your structural score. Your assessment shows by how much." },
      { title: "You make financial and operational decisions knowing your structural floor.", body: "Equipment financing, land commitments, and operating loans need to account for your actual structural position, not optimistic price projections." },
      { title: "You see what forward contracts or a second revenue channel does to your structural score.", body: "Contracted sales are structurally different from open-market sales. Your assessment quantifies the difference." },
      { title: "You understand how lenders evaluate agricultural income.", body: "Agricultural lending is complex. Your score gives you a structural picture of your income before any lender evaluation." },
      { title: "You track structural changes as your contracts, crop mix, and buyer relationships evolve.", body: "Each forward contract signed, each new buyer added, each revenue channel diversified moves your score." },
    ],
    prep: [
      "Know whether you have any contracted sales vs. open market sales",
      "Know how much last year's income varied from a typical year",
      "Think about what % of your income comes from one crop, product, or buyer",
    ],
    professionalHref: "/lenders",
    professionalLabel: "Are you a lender working with agricultural operations?",
    metaTitle: "Income Stability Score for Agriculture — RunPayway™",
    metaDesc: "Agricultural income is exposed to forces you can't control. RunPayway™ scores your farm income structure in under two minutes — market exposure, contract coverage, and what to protect first.",
  },
  {
    slug: "energy-utilities",
    name: "Energy & Utilities",
    badge: "FOR ENERGY & UTILITIES PROFESSIONALS",
    constraint: "One market shift can reprice six months of work overnight.",
    because: "Energy income that looks consistent can hide significant commodity price exposure. When prices move, contracted and spot-market income respond very differently. Your score shows how much of your income is locked in contracted rates versus floating with market conditions.",
    proofA: { income: "$145K / year", desc: "Primarily spot-market pricing. No long-term rate agreements. Revenue moves with commodity prices. One price cycle can reprice the entire year.", score: 38, band: "Developing Stability" },
    proofB: { income: "$130K / year", desc: "60% of output under multi-year contracted rates. Remaining 40% at spot-market pricing. Fixed-rate portion creates a structural floor.", score: 66, band: "Established Stability" },
    outcomes: [
      { title: "You find out how much of your income is structurally protected from commodity price movements.", body: "Contracted rates and spot pricing have entirely different structural profiles. Your score separates them clearly." },
      { title: "You make capital and operational decisions knowing your structural floor under market conditions.", body: "Infrastructure investment and long-term commitments need to be supported by contracted income, not projected market prices." },
      { title: "You see what moving output from spot to contracted rates does to your structural score.", body: "The transition from market-priced to contracted revenue is the most significant structural lever in energy income." },
      { title: "You understand how lenders evaluate energy and utilities income.", body: "Commodity-exposed income is among the most complex to underwrite. Your score gives you a clear structural picture first." },
      { title: "You track structural changes as your contract coverage, pricing mix, and customer base evolves.", body: "Each new contracted rate, each long-term customer agreement, each reduction in spot-market exposure changes your score." },
    ],
    prep: [
      "Know whether your income is tied to commodity prices or contracted rates",
      "Know how much your income varied month-to-month last year",
      "Think about whether your customers are under long-term contracts or spot pricing",
    ],
    professionalHref: "/advisors",
    professionalLabel: "Are you a financial advisor working with energy or utilities professionals?",
    metaTitle: "Income Stability Score for Energy & Utilities Professionals — RunPayway™",
    metaDesc: "Commodity exposure creates hidden structural risk. RunPayway™ scores your energy income structure in under two minutes — contracted vs. spot income, market exposure, and what to lock in first.",
  },
];

export function getIndustryBySlug(slug: string): IndustryPage | undefined {
  return INDUSTRY_PAGES.find((i) => i.slug === slug);
}
