"use client";

import { useState, useEffect, useRef } from "react";
import Link from "next/link";

/* ------------------------------------------------------------------ */
/*  Shared hooks                                                       */
/* ------------------------------------------------------------------ */

const canHover = () =>
  typeof window !== "undefined" && window.matchMedia("(hover: hover)").matches;

function useInView(threshold = 0) {
  const ref = useRef<HTMLDivElement>(null);
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const rect = el.getBoundingClientRect();
    if (rect.top < window.innerHeight + 50 && rect.bottom > 0) {
      setVisible(true);
      return;
    }
    const obs = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setVisible(true);
          obs.disconnect();
        }
      },
      { threshold },
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, [threshold]);
  return { ref, visible };
}

function useMobile(breakpoint = 768) {
  const [mobile, setMobile] = useState(false);
  useEffect(() => {
    const check = () => setMobile(window.innerWidth <= breakpoint);
    check();
    window.addEventListener("resize", check);
    return () => window.removeEventListener("resize", check);
  }, [breakpoint]);
  return mobile;
}

/* ------------------------------------------------------------------ */
/*  Brand tokens                                                       */
/* ------------------------------------------------------------------ */

const B = {
  navy: "#0E1A2B",
  purple: "#4B3FAE",
  teal: "#1F6D7A",
  sand: "#F7F6F3",
  sandDk: "#EDECEA",
  muted: "#6B7280",
  light: "#9CA3AF",
  gradient: "linear-gradient(135deg, #0E1A2B 0%, #4B3FAE 50%, #1F6D7A 100%)",
};

const S = {
  sectionY:     { desktop: 160, mobile: 88 },
  sectionYsm:   { desktop: 120, mobile: 72 },
  transitionY:  { desktop: 72, mobile: 48 },
  disclaimerY:  { desktop: 64, mobile: 48 },
  maxW:         1060,
  padX:         { desktop: 48, mobile: 24 },
  h1mb:         28,
  h2mb:         24,
  subtextMb:    56,
  paraMb:       24,
  labelMb:      16,
  cardPad:      { desktop: 36, mobile: 24 },
  cardRadius:   16,
  panelRadius:  20,
  gridGap:      24,
  gridGapSm:    16,
  ctaH:         56,
  ctaHsm:       46,
  ctaPadX:      32,
  ctaRadius:    14,
  lhHeading:    1.08,
  lhBody:       1.75,
  lhDense:      1.5,
  lsHeading:    "-0.025em",
  lsHero:       "-0.035em",
  lsLabel:      "0.14em",
};


/* ================================================================== */
/* HERO                                                                */
/* ================================================================== */
function Hero() {
  const { ref, visible } = useInView();
  const mobile = useMobile();

  return (
    <section
      ref={ref}
      aria-label="How It Works Hero"
      style={{
        backgroundColor: "#ffffff",
        paddingTop: mobile ? S.sectionY.mobile : S.sectionY.desktop,
        paddingBottom: mobile ? S.sectionYsm.mobile : S.sectionYsm.desktop,
      }}
    >
      <div style={{ maxWidth: S.maxW, marginLeft: "auto", marginRight: "auto", paddingLeft: mobile ? S.padX.mobile : S.padX.desktop, paddingRight: mobile ? S.padX.mobile : S.padX.desktop }}>
        <div
          style={{
            textAlign: "center",
            opacity: visible ? 1 : 0,
            transform: visible ? "translateY(0)" : "translateY(16px)",
            transition: "opacity 0.6s ease-out, transform 0.6s ease-out",
          }}
        >
          <div
            className="text-[11px] uppercase"
            style={{ color: B.teal, fontWeight: 700, letterSpacing: S.lsLabel, marginBottom: 20 }}
          >
            Model RP-2.0
          </div>
          <h1
            className="text-[36px] md:text-[52px]"
            style={{
              color: B.navy,
              fontWeight: 700,
              letterSpacing: S.lsHero,
              lineHeight: S.lhHeading,
              marginBottom: S.h1mb,
            }}
          >
            How It Works
          </h1>
          <p
            className="text-[16px] md:text-[18px]"
            style={{ color: B.muted, lineHeight: S.lhBody, maxWidth: 560, marginLeft: "auto", marginRight: "auto" }}
          >
            Three steps. Under two minutes. A complete structural assessment of your income generated by deterministic rules.
          </p>
        </div>
      </div>
    </section>
  );
}


/* ================================================================== */
/* THREE STEPS                                                         */
/* ================================================================== */
function ThreeSteps() {
  const { ref, visible } = useInView();
  const mobile = useMobile();

  const steps = [
    {
      num: "01",
      title: "Answer Six Questions",
      subtitle: "Under 2 minutes",
      desc: "You provide six structured inputs about your income: how many sources you have, how concentrated they are, how predictable your income is, how far ahead it is committed, what share continues without active work, and your industry category. No bank connection. No credit pull. No documents.",
    },
    {
      num: "02",
      title: "The Model Runs",
      subtitle: "20 deterministic engines",
      desc: "Your inputs pass through 20 deterministic scoring engines that evaluate structural properties of your income. There is no AI, no machine learning, and no human judgment. The same inputs always produce the same score. Every rule is fixed and versioned under Model RP-2.0.",
    },
    {
      num: "03",
      title: "Get Your Full Report",
      subtitle: "5-page assessment",
      desc: "You receive a comprehensive 5-page report with your Income Stability Score, classification band, structural breakdown, stress scenarios, sensitivity analysis, improvement projections, industry-tailored actions, and model verification. The report is yours — private by default, shareable by choice.",
    },
  ];

  return (
    <section
      ref={ref}
      aria-label="Three Steps"
      style={{
        backgroundColor: B.sand,
        paddingTop: mobile ? S.sectionY.mobile : S.sectionY.desktop,
        paddingBottom: mobile ? S.sectionY.mobile : S.sectionY.desktop,
      }}
    >
      <div style={{ maxWidth: S.maxW, marginLeft: "auto", marginRight: "auto", paddingLeft: mobile ? S.padX.mobile : S.padX.desktop, paddingRight: mobile ? S.padX.mobile : S.padX.desktop }}>
        <div style={{ maxWidth: 720, margin: "0 auto" }}>
          {steps.map((step, i) => (
            <div
              key={step.num}
              style={{
                display: "flex",
                gap: mobile ? 20 : 36,
                alignItems: "flex-start",
                marginBottom: i < steps.length - 1 ? 64 : 0,
                opacity: visible ? 1 : 0,
                transform: visible ? "translateY(0)" : "translateY(16px)",
                transition: `opacity 0.6s ease-out ${i * 120}ms, transform 0.6s ease-out ${i * 120}ms`,
              }}
            >
              {/* Step number */}
              <div
                style={{
                  flexShrink: 0,
                  width: mobile ? 48 : 64,
                  height: mobile ? 48 : 64,
                  borderRadius: "50%",
                  background: B.gradient,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                }}
              >
                <span className="text-[18px] md:text-[22px]" style={{ fontWeight: 700, color: "#ffffff" }}>{step.num}</span>
              </div>

              <div style={{ flex: 1 }}>
                <h3 className="text-[22px] md:text-[28px]" style={{ fontWeight: 700, color: B.navy, letterSpacing: S.lsHeading, marginBottom: 6 }}>
                  {step.title}
                </h3>
                <div className="text-[13px]" style={{ color: B.teal, fontWeight: 600, marginBottom: 16 }}>
                  {step.subtitle}
                </div>
                <p className="text-[15px]" style={{ color: B.muted, lineHeight: S.lhBody, margin: 0 }}>
                  {step.desc}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}


/* ================================================================== */
/* WHAT YOU RECEIVE                                                    */
/* ================================================================== */
function WhatYouReceive() {
  const { ref, visible } = useInView();
  const mobile = useMobile();

  const pages = [
    { page: "Page 1", title: "Score & Classification", items: ["Your 0\u2013100 Income Stability Score", "Classification band (Limited, Developing, Established, or High)", "Percentile ranking within your industry", "Income continuity estimate and confidence level"] },
    { page: "Page 2", title: "Why This Score", items: ["Five structural drivers scored individually", "Contribution bars showing each dimension\u2019s weight", "Key strengths and vulnerabilities identified"] },
    { page: "Page 3", title: "What Could Go Wrong", items: ["Multiple stress scenarios with score projections", "Band migration analysis under adverse conditions", "Sensitivity ranking of all income components"] },
    { page: "Page 4", title: "How to Improve", items: ["Ranked improvement opportunities by estimated impact", "Specific structural actions tailored to your profile", "Projected score lift for each recommendation"] },
    { page: "Page 5", title: "Model Verification", items: ["SHA-256 assessment hash for tamper-proof verification", "Model version and generation timestamp", "Reassessment triggers and timing guidance", "Industry-tailored next steps"] },
  ];

  return (
    <section
      ref={ref}
      aria-label="What You Receive"
      style={{
        backgroundColor: "#ffffff",
        paddingTop: mobile ? S.sectionY.mobile : S.sectionY.desktop,
        paddingBottom: mobile ? S.sectionY.mobile : S.sectionY.desktop,
      }}
    >
      <div style={{ maxWidth: S.maxW, marginLeft: "auto", marginRight: "auto", paddingLeft: mobile ? S.padX.mobile : S.padX.desktop, paddingRight: mobile ? S.padX.mobile : S.padX.desktop }}>
        <div
          style={{
            textAlign: "center",
            marginBottom: S.subtextMb,
            opacity: visible ? 1 : 0,
            transform: visible ? "translateY(0)" : "translateY(12px)",
            transition: "opacity 0.5s ease-out, transform 0.5s ease-out",
          }}
        >
          <h2 className="text-[28px] md:text-[40px]" style={{ color: B.navy, fontWeight: 600, letterSpacing: S.lsHeading, marginBottom: 12 }}>
            What you receive
          </h2>
          <p className="text-[15px]" style={{ color: B.muted, lineHeight: S.lhBody, maxWidth: 560, marginLeft: "auto", marginRight: "auto" }}>
            A complete 5-page structural assessment. Not a summary — a full analysis generated by Model RP-2.0.
          </p>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: mobile ? "1fr" : "1fr 1fr", gap: S.gridGap, maxWidth: 800, margin: "0 auto" }}>
          {pages.map((p, i) => (
            <div
              key={p.page}
              style={{
                backgroundColor: B.sand,
                borderRadius: S.cardRadius,
                padding: mobile ? S.cardPad.mobile : S.cardPad.desktop,
                border: "1px solid rgba(14,26,43,0.06)",
                opacity: visible ? 1 : 0,
                transform: visible ? "translateY(0)" : "translateY(12px)",
                transition: `opacity 0.5s ease-out ${i * 80}ms, transform 0.5s ease-out ${i * 80}ms`,
                ...(i === pages.length - 1 && !mobile ? { gridColumn: "1 / -1", maxWidth: 380, justifySelf: "center", width: "100%" } : {}),
              }}
            >
              <div className="text-[10px] uppercase" style={{ color: B.teal, fontWeight: 700, letterSpacing: "0.12em", marginBottom: 10 }}>
                {p.page}
              </div>
              <h3 className="text-[16px]" style={{ fontWeight: 700, color: B.navy, marginBottom: 14 }}>{p.title}</h3>
              <ul style={{ listStyle: "none", padding: 0, margin: 0 }}>
                {p.items.map((item) => (
                  <li key={item} className="text-[13px]" style={{ color: B.muted, lineHeight: 1.6, paddingLeft: 14, position: "relative", marginBottom: 4 }}>
                    <span style={{ position: "absolute", left: 0, color: B.teal }}>&#8226;</span>
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}


/* ================================================================== */
/* CLASSIFICATION SCALE                                                */
/* ================================================================== */
function ClassificationScale() {
  const { ref, visible } = useInView();
  const mobile = useMobile();

  const bands = [
    { range: "0\u201329", label: "Limited", color: "#DC2626", desc: "Fragile structure, high dependence on active work." },
    { range: "30\u201349", label: "Developing", color: "#F59E0B", desc: "Some support exists, but exposure remains." },
    { range: "50\u201374", label: "Established", color: B.teal, desc: "Meaningful stability with structural protection." },
    { range: "75\u2013100", label: "High", color: B.navy, desc: "Durable architecture, less effort-dependent." },
  ];

  return (
    <section
      ref={ref}
      aria-label="Classification Scale"
      style={{
        backgroundColor: B.sand,
        paddingTop: mobile ? S.sectionY.mobile : S.sectionY.desktop,
        paddingBottom: mobile ? S.sectionY.mobile : S.sectionY.desktop,
      }}
    >
      <div style={{ maxWidth: S.maxW, marginLeft: "auto", marginRight: "auto", paddingLeft: mobile ? S.padX.mobile : S.padX.desktop, paddingRight: mobile ? S.padX.mobile : S.padX.desktop }}>
        <div
          style={{
            textAlign: "center",
            marginBottom: S.subtextMb,
            opacity: visible ? 1 : 0,
            transform: visible ? "translateY(0)" : "translateY(12px)",
            transition: "opacity 0.5s ease-out, transform 0.5s ease-out",
          }}
        >
          <h2 className="text-[28px] md:text-[36px]" style={{ color: B.navy, fontWeight: 600, letterSpacing: S.lsHeading, marginBottom: 12 }}>
            Classification scale
          </h2>
          <p className="text-[15px]" style={{ color: B.muted, lineHeight: S.lhBody, maxWidth: 480, marginLeft: "auto", marginRight: "auto" }}>
            Every score maps to a fixed stability band under Model RP-2.0.
          </p>
        </div>

        {/* Spectrum bar */}
        <div style={{ maxWidth: 640, margin: "0 auto" }}>
          <div style={{
            height: 12,
            borderRadius: 6,
            background: B.gradient,
            marginBottom: 20,
            opacity: visible ? 1 : 0,
            transition: "opacity 0.5s ease-out 100ms",
          }} />

          <div style={{ display: "grid", gridTemplateColumns: mobile ? "1fr" : "1fr 1fr 1fr 1fr", gap: mobile ? 12 : 8 }}>
            {bands.map((band, i) => (
              <div
                key={band.label}
                style={{
                  textAlign: "center",
                  opacity: visible ? 1 : 0,
                  transform: visible ? "translateY(0)" : "translateY(8px)",
                  transition: `opacity 0.4s ease-out ${150 + i * 60}ms, transform 0.4s ease-out ${150 + i * 60}ms`,
                }}
              >
                <div style={{ width: 10, height: 10, borderRadius: "50%", backgroundColor: band.color, margin: "0 auto 8px" }} />
                <div className="text-[13px]" style={{ fontWeight: 700, color: B.navy, marginBottom: 2 }}>{band.range}</div>
                <div className="text-[12px]" style={{ fontWeight: 600, color: band.color, marginBottom: 4 }}>{band.label}</div>
                <div className="text-[11px]" style={{ color: B.muted, lineHeight: 1.4 }}>{band.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}


/* ================================================================== */
/* CTA                                                                 */
/* ================================================================== */
function CtaSection() {
  const { ref, visible } = useInView();
  const mobile = useMobile();
  const [hovered, setHovered] = useState(false);

  return (
    <section
      ref={ref}
      aria-label="Call to Action"
      style={{
        backgroundColor: "#ffffff",
        paddingTop: mobile ? S.sectionY.mobile : S.sectionY.desktop,
        paddingBottom: mobile ? S.sectionY.mobile : S.sectionY.desktop,
      }}
    >
      <div style={{ maxWidth: S.maxW, marginLeft: "auto", marginRight: "auto", paddingLeft: mobile ? S.padX.mobile : S.padX.desktop, paddingRight: mobile ? S.padX.mobile : S.padX.desktop }}>
        <div
          style={{
            textAlign: "center",
            opacity: visible ? 1 : 0,
            transform: visible ? "translateY(0)" : "translateY(16px)",
            transition: "opacity 0.6s ease-out, transform 0.6s ease-out",
          }}
        >
          <h2 className="text-[28px] md:text-[40px]" style={{ color: B.navy, fontWeight: 600, letterSpacing: S.lsHeading, marginBottom: S.h2mb }}>
            Ready to see your score?
          </h2>
          <p className="text-[15px] md:text-[16px]" style={{ color: B.muted, lineHeight: S.lhBody, maxWidth: 480, marginLeft: "auto", marginRight: "auto", marginBottom: 40 }}>
            Under two minutes. No bank connection. No credit pull. A complete structural assessment backed by Model RP-2.0.
          </p>
          <Link
            href="/pricing"
            onMouseEnter={() => canHover() && setHovered(true)}
            onMouseLeave={() => setHovered(false)}
            style={{
              display: "inline-flex",
              alignItems: "center",
              justifyContent: "center",
              height: mobile ? S.ctaHsm : S.ctaH,
              paddingLeft: S.ctaPadX,
              paddingRight: S.ctaPadX,
              borderRadius: S.ctaRadius,
              background: hovered ? B.purple : B.gradient,
              color: "#ffffff",
              fontSize: 15,
              fontWeight: 600,
              letterSpacing: "0.01em",
              textDecoration: "none",
              boxShadow: hovered ? "0 8px 24px rgba(75,63,174,0.25)" : "0 4px 16px rgba(14,26,43,0.12)",
              transition: "background 260ms ease, box-shadow 260ms ease",
            }}
          >
            Get My Score
          </Link>
        </div>
      </div>
    </section>
  );
}


/* ================================================================== */
/* MODEL BADGE                                                         */
/* ================================================================== */
function ModelBadge() {
  const mobile = useMobile();

  return (
    <section
      aria-label="Model Badge"
      style={{
        backgroundColor: B.sand,
        paddingTop: mobile ? S.disclaimerY.mobile : S.disclaimerY.desktop,
        paddingBottom: mobile ? S.disclaimerY.mobile : S.disclaimerY.desktop,
      }}
    >
      <div style={{ maxWidth: S.maxW, marginLeft: "auto", marginRight: "auto", paddingLeft: mobile ? S.padX.mobile : S.padX.desktop, paddingRight: mobile ? S.padX.mobile : S.padX.desktop, textAlign: "center" }}>
        <div
          style={{
            display: "inline-flex",
            alignItems: "center",
            gap: 10,
            padding: "10px 20px",
            borderRadius: 100,
            backgroundColor: "#ffffff",
            border: "1px solid rgba(14,26,43,0.06)",
          }}
        >
          <div style={{ width: 8, height: 8, borderRadius: "50%", background: B.gradient }} />
          <span className="text-[12px]" style={{ color: B.navy, fontWeight: 600, letterSpacing: "0.04em" }}>
            Model RP-2.0
          </span>
        </div>
      </div>
    </section>
  );
}


/* ================================================================== */
/* MAIN EXPORT                                                         */
/* ================================================================== */
export default function HowItWorksPage() {
  return (
    <div>
      <Hero />
      <ThreeSteps />
      <WhatYouReceive />
      <ClassificationScale />
      <CtaSection />
      <ModelBadge />
    </div>
  );
}
