"use client";

import {
  LearnHero,
  QuickInsightStrip,
  CoreContent,
  P,
  SystemBlock,
  VisualModel,
  ScenarioBlock,
  ContrastBlock,
  RealityCheck,
  RelatedTopics,
  LearnFAQ,
  MetaFooter,
  StickyLearnCTA,
  ScenarioExtension,
} from "@/components/learn/LearnComponents";

export default function CreatorViralIncomeRisk() {
  return (
    <>
      {/* 1. Hero */}
      <LearnHero
        label="Scenario Analysis"
        title="Creator — Viral Income Risk"
        definition="Viral income creates the illusion of stability through volume. A single viral month can generate more than the previous quarter — but the next month can return to baseline or zero."
        subtitle="Volume is not structure. This analysis explains why viral income is among the most fragile income types the model evaluates."
      />

      {/* 2. Quick Insight Strip */}
      <QuickInsightStrip
        items={[
          "A single viral video can represent 40% or more of annual income — concentrated in one asset on one platform",
          "Platform algorithms are not contractual — they change without notice, consent, or recourse",
          "Audience attention is borrowed, not owned — it cannot be invoiced, retained, or enforced",
        ]}
      />

      {/* 3. Core Content */}
      <CoreContent
        sections={[
          {
            heading: "Why viral income is structurally fragile",
            body: (
              <>
                <P>
                  A creator earning $180,000 annually with 40% of that income attributable to a single viral video is operating with a concentration profile that most income stability models would flag as critical. The viral content performed because of a specific intersection of timing, audience sentiment, platform algorithm behavior, and content resonance. None of these factors are controllable, repeatable, or contractually guaranteed.
                </P>
                <P>
                  The $72,000 generated by that single video is not recurring revenue. It is a one-time event that happened to produce substantial income. The remaining $108,000 — spread across other content, sponsorships, and platform payments — represents the creator&apos;s actual baseline earning capacity. When the viral effect fades, the income does not gradually decline. It reverts to baseline immediately, often within 30-60 days of the viral peak.
                </P>
                <P>
                  The structural problem is that the creator&apos;s financial planning, lifestyle, and business decisions are often calibrated to the $180,000 figure rather than the $108,000 baseline. Tax obligations, team costs, equipment investments, and personal expenses are set against a number that includes a non-repeatable event. The gap between the viral-inflated total and the structural baseline creates financial exposure that compounds over time.
                </P>
              </>
            ),
          },
          {
            heading: "Platform dependency as concentration risk",
            body: (
              <>
                <P>
                  Creator income is uniquely exposed to platform risk because the platform simultaneously controls distribution, monetization, and audience access. A traditional business that depends on a single client can at least negotiate terms, sign contracts, and enforce agreements. A creator who depends on a platform has no contractual right to distribution, no guaranteed monetization rate, and no enforceable claim on audience reach.
                </P>
                <P>
                  Algorithm changes are the creator equivalent of a client termination — except they happen without notice, affect all content simultaneously, and offer no appeal process. A platform that changes its recommendation algorithm can reduce a creator&apos;s reach by 50-80% overnight. The creator&apos;s content quality, posting frequency, and audience relationship have not changed. The platform simply redirected attention elsewhere.
                </P>
                <P>
                  This creates a risk profile where the creator has high effort, high skill, and genuine audience value — but zero structural protection against the platform decisions that determine whether that value translates to income. The model scores this exposure heavily because it represents uncontrollable, uncontractual, and unpredictable risk to the primary income mechanism.
                </P>
              </>
            ),
          },
          {
            heading: "Building durability from viral momentum",
            body: (
              <>
                <P>
                  The optimal response to viral income is not to reject it but to convert it. Viral reach provides temporary access to a large audience. The structural opportunity is to move as many of those audience members as possible from platform-dependent followers to owned-channel subscribers, customers, and contractual partners. Every audience member who moves from a social platform to an email list, paid community, or direct purchase relationship becomes structurally protected income.
                </P>
                <P>
                  Brand partnerships represent another conversion pathway, but only when structured correctly. A brand deal that pays per post is platform-dependent income with a different label. A brand partnership with a six-month minimum commitment, guaranteed payment schedule, and deliverables that span multiple platforms converts attention into contractual revenue. The income becomes protected by agreement rather than dependent on algorithmic performance.
                </P>
                <P>
                  Platform diversification reduces single-platform concentration but does not eliminate platform dependency. A creator earning across three platforms has better distribution than one earning on a single platform, but all three income streams remain algorithmically dependent. True structural improvement requires moving income from platform-dependent to platform-independent channels: direct sales, owned products, contractual partnerships, and subscription models where the creator controls the billing relationship.
                </P>
              </>
            ),
          },
        ]}
      />

      {/* Scenario Extension */}
      <ScenarioExtension
        setup="A creator earning $180,000 annually. One viral video drove approximately 40% of total annual income ($72,000). Remaining income is distributed across ad revenue, sponsorships, and platform creator fund payments. All income flows through a single primary platform. No owned products, no email list monetization, no contractual brand partnerships with guaranteed minimums."
        riskExposure="Platform algorithm dependency — the primary distribution mechanism is controlled entirely by the platform with no contractual guarantees. Audience attention is not contractual — followers can be reached only if the platform chooses to distribute the content. Viral income is non-repeatable — the conditions that produced the viral event are not controllable or reproducible on demand."
        disruption="The platform updates its recommendation algorithm, deprioritizing the content format that produced the viral video. Reach drops 60% within 45 days. Simultaneously, the creator fund payment rate is reduced by 30%. Brand sponsors pause pending performance review. Monthly income drops from the viral-inflated average to below baseline within one billing cycle."
        scoreRange="15-25. The score reflects extreme platform concentration, zero contractual protection on primary revenue, non-repeatable viral income dependency, and the absence of owned-channel revenue. Despite the $180,000 annual figure, the structural profile is among the weakest the model evaluates for earners at this income level."
        howToFix="Build owned audience products (courses, paid communities, direct merchandise). Diversify across multiple platforms to reduce single-platform concentration. Lock brand partnerships with guaranteed minimums and multi-month commitments. Convert platform followers to email subscribers where the creator controls the distribution channel. Target reducing platform-dependent income to below 40% of total revenue within 12 months."
      />

      {/* 4. System Block */}
      <SystemBlock />

      {/* 5. Visual Model */}
      <VisualModel protected={5} recurring={15} atRisk={80} />

      {/* 6. Scenario */}
      <ScenarioBlock
        title="Algorithm change eliminates viral momentum"
        setup="A creator earning $180,000 annually, with $72,000 attributable to a single viral video. All income flows through one platform. No owned products. No contractual brand minimums. No email list revenue."
        risk="The platform updates its content recommendation algorithm, deprioritizing the creator's primary content format. Reach declines 60% over 45 days. The creator fund payment rate is simultaneously reduced. Brand sponsors request performance reviews before renewing."
        outcome="Monthly income drops from $15,000 (viral-inflated average) to $6,000-$8,000 (baseline). Annual run rate falls from $180,000 to approximately $80,000-$96,000. The creator's cost structure — team, equipment, studio lease — was built for $180,000. The gap between structural income and committed expenses creates immediate financial pressure with no contractual remedy available."
      />

      {/* 7. Contrast */}
      <ContrastBlock
        left="Viral Reach"
        right="Durable Revenue"
        explanation="Viral reach is a distribution event — temporary, platform-controlled, and non-repeatable. Durable revenue is a structural characteristic — contractual, owned, and persistent regardless of platform algorithm behavior. A creator with 10 million views and no owned products has viral reach. A creator with 100,000 email subscribers and a paid community has durable revenue. The model measures the structural characteristics, not the visibility metrics."
      />

      {/* 8. Reality Check */}
      <RealityCheck statement="A viral month is not a revenue model. It is a weather event. The creator who builds their financial structure around viral income is building on a foundation that can disappear with a single algorithm update." />

      {/* 9. Related Topics */}
      <RelatedTopics
        links={[
          { href: "/learn/income-stability-creators", label: "Income Stability for Creators" },
          { href: "/learn/creator-brand-deals-vs-mixed-income", label: "Scenario: Creator — Brand Deals vs Mixed Income" },
          { href: "/learn/income-concentration-risk", label: "Income Concentration Risk" },
          { href: "/learn/active-vs-passive-income-stability", label: "Active vs Passive Income Stability" },
          { href: "/learn/income-fragility-explained", label: "Income Fragility Explained" },
        ]}
      />

      {/* 10. FAQ */}
      <LearnFAQ
        items={[
          {
            q: "Can viral income ever contribute to a high stability score?",
            a: "Not directly. Viral income by definition is non-repeatable and platform-dependent — two characteristics that the model scores as structurally weak. However, viral income that is converted into owned products, email subscribers, or contractual partnerships can indirectly improve stability by funding the creation of durable revenue streams. The viral event itself does not improve the score, but the structural investments it funds can.",
          },
          {
            q: "How does the model distinguish between creator income types?",
            a: "The model evaluates each income stream on its structural characteristics: contractual protection, recurrence pattern, platform dependency, and concentration. Ad revenue from a platform creator fund scores differently than a six-month brand partnership with guaranteed minimums, which scores differently than direct product sales through an owned storefront. The label 'creator income' is not a single category — it is a collection of structurally distinct income types.",
          },
          {
            q: "What is the fastest way for a creator to improve their score?",
            a: "Lock one or two brand partnerships with guaranteed minimum payments and multi-month terms. This converts platform-dependent, performance-based income into contractual recurring revenue. A single $3,000/month brand partnership with a six-month commitment adds $18,000 in protected forward revenue — a meaningful structural improvement that can be executed within 30-60 days.",
          },
          {
            q: "Does platform diversification meaningfully improve the score?",
            a: "It improves concentration metrics by reducing single-platform dependency, but it does not address the underlying structural weakness of algorithmic income. A creator earning across three platforms has better distribution, but all three streams remain platform-controlled and algorithmically dependent. True structural improvement requires moving income from platform-dependent to platform-independent channels.",
          },
          {
            q: "How should a creator think about their 'real' income level?",
            a: "Strip out any income attributable to one-time viral events and calculate the trailing 12-month average excluding the top-performing month. This produces a conservative baseline that more accurately reflects structural earning capacity. Financial planning, tax provisioning, and expense commitments should be calibrated to this baseline figure, not the viral-inflated total.",
          },
        ]}
      />

      {/* 11. Micro Conversion */}

      {/* 12. CTA */}

      {/* 13. Meta Footer */}
      <MetaFooter updated="April 2026" />
      <StickyLearnCTA />
    </>
  );
}
