"use client";

import {
  LearnHero,
  QuickInsightStrip,
  CoreContent,
  P,
  SystemBlock,
  VisualModel,
  ScenarioBlock,
  ContrastBlock,
  RealityCheck,
  RelatedTopics,
  LearnFAQ,
  MicroConversion,
  LearnCTA,
  MetaFooter,
  ScenarioExtension,
} from "@/components/learn/LearnComponents";

export default function LawyerHourlyVsRetainer() {
  return (
    <>
      {/* 1. Hero */}
      <LearnHero
        label="Scenario Analysis"
        title="Lawyer — Hourly vs Retainer"
        definition="The same legal practice billed hourly and billed on retainer produces the same work — but completely different income stability."
        subtitle="How billing structure transforms income resilience without changing the underlying practice."
      />

      {/* 2. Quick Insight Strip */}
      <QuickInsightStrip
        items={[
          "Hourly billing creates income that resets to zero each month",
          "Retainer billing creates contractually committed forward revenue",
          "Same practice, same clients — 30+ point difference in stability score",
        ]}
      />

      {/* 3. Core Content */}
      <CoreContent
        sections={[
          {
            heading: "Two billing models, same legal work",
            body: (
              <>
                <P>
                  Consider a solo practitioner or small firm attorney earning $250,000 annually. Under an hourly billing model, this revenue is generated by billing approximately 1,250 hours at an average effective rate of $200 per hour. Each hour must be worked, recorded, billed, and collected. Revenue in any given month depends on the number of billable hours produced that month, the complexity and value of the matters worked on, and the client&apos;s willingness and ability to pay invoices on a timely basis.
                </P>
                <P>
                  Under a retainer billing model, the same $250,000 is generated through monthly retainer agreements with a portfolio of clients. Each client pays a fixed monthly fee — ranging from $2,000 to $8,000 depending on scope — in exchange for a defined allocation of the attorney&apos;s time and availability. The attorney provides the same legal services, applies the same expertise, and delivers the same quality of work. The difference is entirely in the billing and payment structure.
                </P>
                <P>
                  The work itself does not change. The attorney&apos;s skills, practice areas, client relationships, and professional value are identical under both models. What changes is the income structure — the mechanism by which legal work is converted into revenue. This structural difference produces measurably different stability profiles, because the scoring model evaluates how income is organized, not how it is earned.
                </P>
              </>
            ),
          },
          {
            heading: "Why hourly billing suppresses stability scores",
            body: (
              <>
                <P>
                  Hourly billing produces income with no forward visibility. On the first of each month, the attorney&apos;s committed income for that month is $0. Revenue will be generated only if clients bring matters that require work, the attorney performs and records that work, invoices are issued, and payments are collected. Each step introduces uncertainty. A month with fewer client matters, a complex matter that requires extensive unbillable preparation, or a client who delays payment can reduce monthly income significantly below the annual average.
                </P>
                <P>
                  Matter conclusion risk is the primary structural vulnerability. Legal matters are finite — a transaction closes, a case settles, a dispute is resolved. When a matter concludes, the revenue associated with that client&apos;s matter ends. If two major matters conclude simultaneously, the attorney may face a sharp revenue decline even if new matters are in the pipeline. The pipeline provides no structural protection because pipeline matters have not yet generated any billable hours or committed any revenue.
                </P>
                <P>
                  Collection risk adds a second structural layer. Hourly billing typically involves billing after work is performed, with payment terms of 30 to 60 days. The attorney delivers value in month one, invoices in month two, and receives payment in month three. This lag means that revenue disruptions — client non-payment, fee disputes, or matter scope reductions — are not felt until weeks after the underlying cause. The delay between work performed and cash received creates a structural buffer for the client and a structural vulnerability for the attorney.
                </P>
              </>
            ),
          },
          {
            heading: "How retainer billing transforms the stability profile",
            body: (
              <>
                <P>
                  A retainer agreement converts variable hourly income into contractually committed monthly revenue. A client paying $5,000 per month on a twelve-month retainer has committed $60,000 in revenue with defined terms. The attorney knows on January 1 that this client will generate $5,000 per month for the duration of the agreement, regardless of how many hours are worked in any given month. This forward visibility is a structural characteristic that improves income stability.
                </P>
                <P>
                  The commitment period provides protection against matter conclusion risk. When a retainer client&apos;s individual matter concludes, the retainer continues. The client remains engaged and continues paying the monthly fee because the retainer covers ongoing legal availability, not a specific matter. This structural feature eliminates the income disruption that occurs in hourly billing when matters end. The attorney&apos;s revenue continues even during periods between active matters for a given client.
                </P>
                <P>
                  Payment timing shifts in the attorney&apos;s favor under retainer billing. Retainers are typically paid at the beginning of each month — the client pays for the coming month&apos;s availability, not for the prior month&apos;s work. This advance payment eliminates the collection lag inherent in hourly billing and removes the collection risk for the covered period. The attorney has cash in hand before performing any work, which is a fundamentally different cash flow structure than billing after the fact and waiting 30-60 days for payment.
                </P>
              </>
            ),
          },
        ]}
      />

      {/* Scenario Extension */}
      <ScenarioExtension
        setup="Both practices generate $250,000 annually. Hourly practice: 1,250 billable hours at $200/hour average effective rate, 15 active clients, billing monthly in arrears with 30-45 day collection. Retainer practice: 25 retainer clients paying $500-$8,000/month, 12-month agreements, billed at the beginning of each month. Same attorney, same practice areas, same level of expertise."
        riskExposure="Hourly: zero committed forward revenue at any point. Income depends entirely on matters in progress and hours billed. Two major matters concluding simultaneously can reduce monthly income by 40-60%. Retainer: $20,800 in committed monthly revenue ($250,000 / 12) with contractual terms. Client departures are staggered across renewal dates. Loss of the largest retainer client reduces monthly income by approximately $8,000 (less than 4% of annual revenue)."
        disruption="Two major matters conclude simultaneously. For the hourly practice, this eliminates approximately $8,000 per month in billings — a 38% reduction in monthly revenue — with no replacement revenue committed. For the retainer practice, the same two clients' matters conclude but their retainers continue. Monthly revenue is unchanged because the retainer covers ongoing availability, not specific matters."
        scoreRange="Hourly practice: 30-40. No forward revenue commitment, matter conclusion risk, and collection lag create structural instability despite consistent billing history. Retainer practice: 60-75. Contractually committed forward revenue, advance payment, and protection against matter conclusion risk produce a fundamentally stronger stability profile. Same annual income, same practice, 30+ point score difference."
        howToFix="Convert top five hourly clients to annual retainer agreements. Start with clients who generate consistent monthly billings — they are already paying retainer-level amounts without the structural commitment. Frame the retainer as a benefit: guaranteed availability, predictable monthly cost, priority responsiveness. Target converting 50-60% of hourly revenue to retainer revenue within 12 months. Each conversion directly improves the stability score."
      />

      {/* 4. System Block */}
      <SystemBlock />

      {/* 5. Visual Model */}
      <VisualModel protected={30} recurring={40} atRisk={30} />

      {/* 6. Scenario */}
      <ScenarioBlock
        title="Two matters close in the same week — two different outcomes"
        setup="An attorney's two largest clients both reach resolution in their primary matters during the same week in September. Client A's litigation settles. Client B's transaction closes. Combined, these two matters have generated approximately $8,000 per month in billings for the past six months. Both clients indicate they have no immediate follow-on matters."
        risk="For the hourly attorney: monthly revenue drops from approximately $21,000 to $13,000 — a 38% reduction — with no structural mechanism to replace the lost billings. New matters must be sourced, onboarded, and billed before revenue recovers. Timeline: 6-12 weeks to restore previous billing levels, assuming new matters materialize. For the retainer attorney: monthly revenue is unchanged. Both clients continue paying their retainer fees for the duration of the agreement, regardless of active matter status."
        outcome="Hourly attorney: estimated income loss over the recovery period of $16,000-$24,000. The attorney must accelerate business development while managing a reduced income. Retainer attorney: $0 income loss. The retainer structure absorbs the matter conclusion entirely. The attorney continues providing legal availability under the existing agreements and uses the reduced active workload to deepen other client relationships."
      />

      {/* 7. Contrast */}
      <ContrastBlock
        left="Billable Hours"
        right="Monthly Retainer"
        explanation="Billable hours measure work performed. Monthly retainer measures commitment secured. An attorney billing 120 hours per month has high utilization but no forward revenue guarantee — next month's income depends on next month's matters. An attorney with $20,000 in monthly retainer commitments has guaranteed forward revenue regardless of how many hours any individual matter requires. The structural difference is between earning income and having income committed."
      />

      {/* 8. Reality Check */}
      <RealityCheck statement="Hourly billing means your income ends the moment your current matters do. Retainer billing means it does not." />

      {/* 9. Related Topics */}
      <RelatedTopics
        links={[
          { href: "/learn/what-is-income-stability", label: "What Is Income Stability" },
          { href: "/learn/income-stability-lawyers", label: "Income Stability for Lawyers" },
          { href: "/learn/income-stability-consultants", label: "Income Stability for Consultants" },
          { href: "/learn/consultant-no-contracts-vs-retainers", label: "Scenario: Consultant — No Contracts vs Retainers" },
        ]}
      />

      {/* 10. FAQ */}
      <LearnFAQ
        items={[
          {
            q: "Won't clients resist switching from hourly to retainer?",
            a: "Some will, but many clients prefer predictable monthly legal costs over variable hourly invoices that fluctuate month to month. Frame the retainer as a budgeting tool for the client: a fixed monthly cost that includes priority access and defined services. Start with clients who already generate consistent monthly billings — they are effectively paying a retainer without the formal structure. Formalizing it benefits both parties.",
          },
          {
            q: "What if I work more hours than the retainer covers?",
            a: "Retainer agreements typically include provisions for work exceeding the allocated hours — either billed at a discounted hourly rate or triggering a retainer adjustment discussion. The retainer covers a defined scope of availability and work. Extraordinary matters outside that scope are handled through supplemental billing. The structural benefit of the retainer — committed monthly revenue — is not diminished by occasional supplemental billing.",
          },
          {
            q: "How many retainer clients do I need to match my hourly income?",
            a: "The math depends on your retainer pricing and current hourly income. An attorney earning $250,000 from hourly billing can match that income with 25 retainer clients averaging $833/month, 15 clients averaging $1,389/month, or 10 clients averaging $2,083/month. Fewer, higher-value retainers create some concentration risk. A portfolio of 15-25 clients at varied retainer levels provides both income matching and structural diversification.",
          },
          {
            q: "Does a hybrid model — some hourly, some retainer — improve the score?",
            a: "Yes. Any shift from hourly to retainer improves the structural profile. A practice that converts 50% of revenue to retainer billing creates a meaningful income floor while maintaining hourly flexibility for matters that do not fit a retainer structure. The score improvement is proportional to the percentage of revenue that is structurally committed. Even 30% retainer revenue materially improves the stability score compared to 100% hourly.",
          },
          {
            q: "Are flat-fee arrangements the same as retainers for scoring purposes?",
            a: "No. A flat fee for a specific matter is a project-based payment — it concludes when the matter concludes. A retainer is a recurring commitment that persists regardless of individual matter status. Flat fees are structurally similar to hourly billing in that they are matter-dependent. Retainers are structurally different because they are relationship-dependent and continue between matters. The scoring model distinguishes between these billing structures.",
          },
        ]}
      />

      {/* 11. Micro Conversion */}
      <MicroConversion
        items={[
          { text: "See a Sample Report", href: "/sample-report" },
          { text: "Score Your Legal Practice", href: "/begin" },
        ]}
      />

      {/* 12. CTA */}
      <LearnCTA
        heading="Find Out Where You Stand"
        sub="Get your income stability score and see how your billing structure affects your practice's resilience."
      />

      {/* 13. Meta Footer */}
      <MetaFooter updated="April 2026" />
    </>
  );
}
