"use client";

import {
  LearnHero,
  QuickInsightStrip,
  CoreContent,
  P,
  SystemBlock,
  VisualModel,
  ScenarioBlock,
  ContrastBlock,
  RealityCheck,
  RelatedTopics,
  LearnFAQ,
  LearnCTA,
  StickyLearnCTA,
  MetaFooter,
  ScenarioExtension,
} from "@/components/learn/LearnComponents";

export default function PassiveIncomeIllusion() {
  return (
    <>
      {/* 1. Hero */}
      <LearnHero
        label="Scenario Analysis"
        title="Passive Income Illusion"
        definition="Most income marketed as 'passive' requires ongoing effort, platform dependency, or capital at risk. True income passivity — income that continues with zero effort — is rare and often overstated."
        subtitle="The model does not accept labels at face value. This analysis explains how it evaluates income that claims to be passive."
      />

      {/* 2. Quick Insight Strip */}
      <QuickInsightStrip
        items={[
          "Rental income requires property management, tenant relations, and capital maintenance — it is labor-reduced, not labor-free",
          "Digital product income depends on platform algorithms that the creator does not control and cannot contractually secure",
          "Dividend income is genuinely passive but carries market risk that can reduce the income-generating capital by 30-50% in a downturn",
        ]}
      />

      {/* 3. Core Content */}
      <CoreContent
        sections={[
          {
            heading: "Deconstructing the passive label",
            body: (
              <>
                <P>
                  The term &quot;passive income&quot; has become one of the most imprecise concepts in personal finance. It is applied to income streams ranging from dividend portfolios (genuinely passive) to rental properties (labor-reduced but not passive) to digital product sales (platform-dependent and often requiring ongoing marketing effort). The income stability model does not use the passive label as a scoring input. It evaluates each stream on its actual structural characteristics: labor dependency, contractual protection, platform risk, recurrence pattern, and capital exposure.
                </P>
                <P>
                  A professional earning $150,000 annually from three sources labeled as &quot;passive&quot; — $80,000 from rental income, $40,000 from digital products, and $30,000 from dividends — appears to have achieved the financial independence that passive income promises. The structural reality is more complex. The rental income requires 10-15 hours per week of management effort and carries vacancy risk. The digital product income depends on platform search algorithms and requires periodic content updates. The dividend income is genuinely passive but is generated by capital that fluctuates with market conditions.
                </P>
                <P>
                  The model evaluates this profile not as &quot;passive income&quot; but as three distinct streams with different structural characteristics: a labor-reduced, asset-dependent stream (rental); a platform-dependent, semi-active stream (digital products); and a capital-dependent, genuinely passive stream (dividends). Each carries different risks, requires different maintenance, and responds differently to disruption. The combined profile scores based on these structural realities, not on the passive label that unifies them in common financial discourse.
                </P>
              </>
            ),
          },
          {
            heading: "The structural risks within each 'passive' stream",
            body: (
              <>
                <P>
                  Rental income at $80,000 from a portfolio of properties provides genuine diversification from employment income and continues regardless of the owner&apos;s professional employment status. These are structural strengths. The risks are asset-specific: vacancy eliminates income from a unit while carrying costs continue, major repairs can consume months of rental profit, and property management — whether self-managed or outsourced — requires ongoing attention. A two-unit vacancy in a six-unit portfolio reduces rental income by 33% while only reducing expenses by the variable portion. The model scores rental income based on occupancy patterns, lease terms, and the ratio of net rental income to carrying costs.
                </P>
                <P>
                  Digital product income at $40,000 occupies a structural category that the model treats with particular scrutiny. The products may have been created in the past, but the income they generate depends on platform discovery algorithms, search rankings, and marketplace visibility that the creator does not control. A platform that changes its search algorithm, introduces competing products, or modifies its commission structure can reduce digital product income by 40-70% without the creator changing anything. This is platform dependency risk — structurally identical to a creator&apos;s algorithmic exposure.
                </P>
                <P>
                  Dividend income at $30,000 from a portfolio is the closest to genuinely passive income in this profile. The dividends arrive without effort, the underlying companies make the payment decisions, and the income is not platform-dependent. However, the capital that generates $30,000 in dividends (approximately $750,000-$1,000,000 at current yields) is exposed to market risk. A 40% market decline reduces the capital base to $450,000-$600,000, and companies under financial pressure frequently reduce or eliminate dividends. The income is passive, but the capital that produces it is not risk-free.
                </P>
              </>
            ),
          },
          {
            heading: "Building genuinely resilient non-labor income",
            body: (
              <>
                <P>
                  The structural path to resilient non-labor income focuses on reducing the specific vulnerabilities within each stream rather than pursuing more streams with the same passive label. For rental income, the improvement path is longer lease terms, property management automation, and maintaining a capital reserve for vacancy and repairs. Each of these reduces the management burden and financial volatility of the rental stream without changing the income amount.
                </P>
                <P>
                  For digital product income, the structural improvement is platform diversification and the creation of direct sales channels. A digital product that sells through three marketplaces and the creator&apos;s own website has meaningfully lower platform concentration than one that sells exclusively through a single marketplace. Additionally, building an email list and direct customer relationships allows the creator to market products independent of any platform&apos;s algorithm. The model scores multi-platform digital income significantly higher than single-platform digital income.
                </P>
                <P>
                  For dividend income, the structural improvement is portfolio diversification across sectors, geographies, and dividend growth histories. A portfolio concentrated in one sector (e.g., energy or REITs) carries correlation risk that can reduce dividends across the portfolio simultaneously. Broad diversification ensures that sector-specific downturns affect a portion of the portfolio rather than the whole. The model also scores dividend growth stocks — companies with 10+ years of consecutive dividend increases — as more structurally reliable than high-yield stocks with shorter track records.
                </P>
              </>
            ),
          },
        ]}
      />

      {/* Scenario Extension */}
      <ScenarioExtension
        setup="A professional with $150,000 in annual income from three 'passive' sources: rental income at $80,000 (53%) from a six-unit residential portfolio, digital product sales at $40,000 (27%) from courses and templates on a single marketplace platform, and dividend income at $30,000 (20%) from a $850,000 equity portfolio. No W-2 employment. No active freelance work."
        riskExposure="Rental income carries vacancy risk (currently one unit vacant = $13,300 annual loss), maintenance capital requirements, and 10-15 hours/week management effort. Digital product income depends entirely on a single platform's search algorithm and commission structure. Dividend income is genuinely passive but capital is exposed to market risk. The combination creates a profile where each stream appears passive but carries distinct structural vulnerabilities."
        disruption="A rental vacancy in a second unit coincides with the marketplace platform changing its search algorithm, reducing digital product visibility by 55%. Rental income drops from $80,000 to $53,400 (two units vacant). Digital product income drops from $40,000 to $18,000. Dividend income is unchanged at $30,000. Total income falls from $150,000 to $101,400 — a 32% decline from two simultaneous events affecting two of three 'passive' streams."
        scoreRange="40-55. The score reflects genuine diversification from employment (positive), three independent income sources (positive), but single-platform dependency on digital products (negative), management effort requirements on rental income (moderate negative), and market exposure on dividend capital (moderate negative). The profile scores in the moderate range because the structural characteristics are mixed despite the passive label."
        howToFix="Automate rental property management through a professional management company to reduce labor dependency. Diversify digital products across three or more platforms and build direct sales capability through an owned website. Diversify the dividend portfolio across sectors and geographies. Build contractual recurring income through annual rental leases with automatic renewal. Target reducing any single vulnerability's potential impact to below 15% of total income."
      />

      {/* 4. System Block */}
      <SystemBlock />

      {/* 5. Visual Model */}
      <VisualModel protected={20} recurring={40} atRisk={40} />

      {/* 6. Scenario */}
      <ScenarioBlock
        title="Dual disruption reveals structural vulnerabilities"
        setup="A professional earning $150,000 from three 'passive' sources: $80,000 rental (six units, one vacant), $40,000 digital products (single marketplace), $30,000 dividends ($850,000 portfolio). No employment income. Financial obligations of $8,200/month."
        risk="A second rental unit becomes vacant when the tenant relocates (combined vacancy now 33% of units). Simultaneously, the marketplace platform restructures its search algorithm, prioritizing newer content. The professional's digital products — created 2-3 years ago — lose 55% of their visibility. The dividend portfolio is unaffected."
        outcome="Monthly income drops from $12,500 to $8,450. With obligations at $8,200, the margin is $250/month — effectively zero financial cushion. Filling the rental vacancy takes 45-60 days. Recovering digital product visibility requires creating new content and rebuilding search ranking — a 3-6 month process. The professional who appeared financially independent now operates at break-even with no buffer against any additional disruption."
      />

      {/* 7. Contrast */}
      <ContrastBlock
        left="Passive Label"
        right="Passive Reality"
        explanation="The passive label describes how income is marketed — minimal effort, automatic earnings, financial freedom. The passive reality describes the structural characteristics of each stream — the actual effort required, the platform dependencies involved, the capital at risk, and the vulnerability to disruption. The model measures reality, not labels. A rental portfolio requires management. Digital products require platform access. Dividends require capital preservation. Each carries structural risks that the passive label obscures."
      />

      {/* 8. Reality Check */}
      <RealityCheck statement="If your 'passive' income requires 15 hours a week of management, depends on a platform algorithm you don't control, and is generated by capital that can decline 40% in a downturn — it is not passive. It is labor-reduced, platform-dependent, and capital-at-risk income with a better marketing name." />

      {/* 9. Related Topics */}
      <RelatedTopics
        links={[
          { href: "/learn/active-vs-passive-income-stability", label: "Active vs Passive Income Stability" },
          { href: "/learn/recurring-vs-non-recurring-income", label: "Recurring vs Non-Recurring Income" },
          { href: "/learn/income-concentration-risk", label: "Income Concentration Risk" },
          { href: "/learn/what-makes-income-stable", label: "What Makes Income Stable" },
          { href: "/learn/income-fragility-explained", label: "Income Fragility Explained" },
        ]}
      />

      {/* 10. FAQ */}
      <LearnFAQ
        items={[
          {
            q: "Is any income truly passive?",
            a: "Dividend income from a broadly diversified portfolio is the closest to genuinely passive — it requires no effort, no platform, and no management beyond periodic portfolio review. Government bond interest and certain annuity payments also qualify. However, all genuinely passive income requires capital that was accumulated through active effort and remains exposed to market risk. The model acknowledges the passivity of the income stream while separately evaluating the risk to the capital that produces it.",
          },
          {
            q: "How does the model score rental income compared to employment income?",
            a: "Rental income scores well on labor independence (it continues if you cannot work) and poorly on management effort and vacancy risk. Employment income scores well on recurrence and contractual protection and poorly on labor dependency and concentration. Neither is categorically better — they carry different structural characteristics. A profile with both rental and employment income scores higher than either alone because the diversification provides structural resilience that neither source provides independently.",
          },
          {
            q: "Should I stop calling my income passive?",
            a: "The label does not affect the model's assessment. Call it whatever is useful for your own financial planning. What matters structurally is understanding the actual characteristics of each stream: how much effort it requires, what platforms or entities it depends on, what risks the underlying capital faces, and what happens to the income if any of those factors change. The model evaluates these characteristics regardless of the label applied to the income.",
          },
          {
            q: "What is the best ratio of passive to active income for stability?",
            a: "The model does not prescribe a ratio because the quality of each stream matters more than the category. A portfolio of well-structured active income (multiple clients, retainer agreements, contractual protection) can score higher than a portfolio of poorly structured passive income (single-platform digital products, concentrated rental property, high-yield dividend stocks). The structural goal is diversification across labor-dependent and labor-independent sources, with contractual protection and recurrence on each.",
          },
        ]}
      />

      {/* 11. Micro Conversion */}

      {/* 12. CTA */}
      <LearnCTA
        heading="Measure What Your Income Actually Is"
        sub="Get your income stability score and understand the structural reality behind your income streams — beyond the labels."
      />

      {/* 13. Meta Footer */}
      <MetaFooter updated="April 2026" />
      <StickyLearnCTA />
    </>
  );
}
