export function generateStaticParams() {
  return [
    // Core (25)
    { slug: "what-is-income-stability" },
    { slug: "income-stability-explained" },
    { slug: "how-to-measure-income-stability" },
    { slug: "income-stability-vs-credit-score" },
    { slug: "income-stability-vs-income" },
    { slug: "income-stability-vs-net-worth" },
    { slug: "what-is-income-structure" },
    { slug: "income-structure-explained" },
    { slug: "what-makes-income-stable" },
    { slug: "what-makes-income-unstable" },
    { slug: "income-risk-explained" },
    { slug: "income-fragility-explained" },
    { slug: "income-continuity-explained" },
    { slug: "income-concentration-risk" },
    { slug: "active-vs-passive-income-stability" },
    { slug: "recurring-vs-non-recurring-income" },
    { slug: "predictable-vs-unpredictable-income" },
    { slug: "how-income-breaks-under-pressure" },
    { slug: "structural-income-risk-explained" },
    { slug: "income-stability-index" },
    { slug: "income-stress-testing-explained" },
    { slug: "income-dependency-explained" },
    { slug: "how-stable-is-your-income" },
    { slug: "is-my-income-stable" },
    { slug: "how-to-improve-income-stability" },
    // Industry (15)
    { slug: "income-stability-real-estate-agents" },
    { slug: "income-stability-freelancers" },
    { slug: "income-stability-consultants" },
    { slug: "income-stability-sales-professionals" },
    { slug: "income-stability-insurance-agents" },
    { slug: "income-stability-mortgage-brokers" },
    { slug: "income-stability-lawyers" },
    { slug: "income-stability-doctors" },
    { slug: "income-stability-contractors" },
    { slug: "income-stability-creators" },
    { slug: "income-stability-tech-workers" },
    { slug: "income-stability-small-business-owners" },
    { slug: "income-stability-retail-owners" },
    { slug: "income-stability-hospitality-workers" },
    { slug: "income-stability-transportation-workers" },
    // Scenarios (25)
    { slug: "150k-freelancer-one-client" },
    { slug: "150k-freelancer-five-clients" },
    { slug: "200k-realtor-commission-heavy" },
    { slug: "200k-realtor-diversified-pipeline" },
    { slug: "consultant-no-contracts-vs-retainers" },
    { slug: "sales-rep-base-plus-commission" },
    { slug: "business-owner-one-vs-three-sources" },
    { slug: "creator-brand-deals-vs-mixed-income" },
    { slug: "contractor-project-based-risk" },
    { slug: "lawyer-hourly-vs-retainer" },
    { slug: "doctor-salary-vs-private-practice" },
    { slug: "insurance-renewal-vs-new-business" },
    { slug: "mortgage-refi-dependent" },
    { slug: "freelancer-no-recurring-income" },
    { slug: "freelancer-50-percent-retainer" },
    { slug: "real-estate-boom-vs-slow-market" },
    { slug: "sales-high-performer-risk" },
    { slug: "consultant-high-income-low-stability" },
    { slug: "creator-viral-income-risk" },
    { slug: "small-business-seasonal-risk" },
    { slug: "multi-income-professional" },
    { slug: "single-income-earner" },
    { slug: "passive-income-illusion" },
    { slug: "income-drop-40-percent" },
    { slug: "stop-working-30-days" },
  ];
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
