import type { Metadata } from "next";
import PageContainer from "@/components/layout/PageContainer";
import ContactForm from "@/components/contact/ContactForm";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Contact \u2014 RunPayway\u2122",
  description:
    "Contact RunPayway for general questions, access issues, report delivery problems, or billing concerns.",
};

export default function ContactPage() {
  return (
    <section className="py-16 md:py-24 bg-white">
      <PageContainer>
        <div className="max-w-[700px] mx-auto">
          <h1 className="text-3xl md:text-4xl font-bold text-navy-900 mb-6">
            Contact
          </h1>

          <p className="text-gray-700 leading-relaxed mb-6">
            If you have a question about RunPayway&#8482;, you&apos;re in the
            right place.
          </p>

          <p className="text-gray-700 leading-relaxed mb-2">
            This page is used for:
          </p>
          <ul className="list-disc pl-6 text-gray-700 space-y-1 mb-8">
            <li>General questions</li>
            <li>Access issues</li>
            <li>Report delivery problems</li>
            <li>Billing or checkout concerns</li>
          </ul>

          <p className="text-gray-700 leading-relaxed mb-2">
            RunPayway&#8482; is a structured diagnostic tool. Support is focused
            on helping you access, receive, and understand what you purchased.
          </p>

          <hr className="border-gray-200 my-10" />

          {/* How to Reach Us */}
          <h2 className="text-2xl font-semibold text-navy-900 mb-4">
            How to Reach Us
          </h2>
          <p className="text-gray-700 leading-relaxed mb-2">
            Please use the contact form below.
          </p>
          <p className="text-gray-700 leading-relaxed mb-2">
            To help us assist you quickly, include:
          </p>
          <ul className="list-disc pl-6 text-gray-700 space-y-1 mb-4">
            <li>Your email address</li>
            <li>The email used at checkout (if different)</li>
            <li>A brief description of the issue</li>
          </ul>
          <p className="text-sm text-gray-500 mb-10">
            For your protection, please do not include sensitive financial
            information.
          </p>

          {/* Contact Form */}
          <ContactForm />

          <hr className="border-gray-200 my-10" />

          {/* What to Expect */}
          <h2 className="text-2xl font-semibold text-navy-900 mb-4">
            What to Expect
          </h2>
          <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-6">
            <li>Messages are reviewed manually</li>
            <li>
              Typical response window:{" "}
              <strong>1&ndash;2 business days</strong>
            </li>
            <li>
              Time-sensitive payment or access issues are prioritized
            </li>
          </ul>
          <p className="text-gray-700 leading-relaxed mb-10">
            Sending one clear message helps us respond faster than multiple
            follow-ups.
          </p>

          <hr className="border-gray-200 my-10" />

          {/* Important Notes */}
          <h2 className="text-2xl font-semibold text-navy-900 mb-4">
            Important Notes
          </h2>
          <ul className="list-disc pl-6 text-gray-700 space-y-2">
            <li>
              RunPayway&#8482; does not provide financial, legal, or tax advice.
            </li>
            <li>
              Reports generated by RunPayway&#8482; are automated and
              non-customized.
            </li>
            <li>Results cannot be modified after generation.</li>
            <li>
              For information on how data is handled, please review our{" "}
              <Link
                href="/privacy"
                className="text-navy-900 underline underline-offset-2 hover:text-navy-700"
              >
                Privacy Policy
              </Link>
              .
            </li>
            <li>
              For purchase terms and refund details, please review our{" "}
              <Link
                href="/terms"
                className="text-navy-900 underline underline-offset-2 hover:text-navy-700"
              >
                Terms &amp; Conditions
              </Link>
              .
            </li>
          </ul>
        </div>
      </PageContainer>
    </section>
  );
}
