"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";

function Divider() {
  return <hr className="border-divider my-12" />;
}

interface Question {
  id: string;
  number: number;
  title: string;
  prompt: string;
  definition: string;
  options: { letter: string; label: string }[];
}

const questions: Question[] = [
  {
    id: "q1",
    number: 1,
    title: "Recurring Revenue Base",
    prompt:
      "What percentage of your total income is contractually recurring or automatically renewing under enforceable agreement?",
    definition:
      '\u201cRecurring\u201d refers to revenue that renews without requiring new client acquisition.',
    options: [
      { letter: "A", label: "0\u201310%" },
      { letter: "B", label: "11\u201330%" },
      { letter: "C", label: "31\u201360%" },
      { letter: "D", label: "61\u201385%" },
      { letter: "E", label: "86\u2013100%" },
    ],
  },
  {
    id: "q2",
    number: 2,
    title: "Income Concentration",
    prompt:
      "Over the last 12 months, what percentage of your total income was generated by your single largest income source?",
    definition:
      '\u201cIncome source\u201d refers to a client, employer, contract group, or asset category.',
    options: [
      { letter: "A", label: "90\u2013100%" },
      { letter: "B", label: "70\u201389%" },
      { letter: "C", label: "50\u201369%" },
      { letter: "D", label: "30\u201349%" },
      { letter: "E", label: "Under 30%" },
    ],
  },
  {
    id: "q3",
    number: 3,
    title: "Income Source Count",
    prompt:
      "Over the last 12 months, how many distinct income sources each contributed 10% or more of your total income?",
    definition:
      "Each source must independently meet the 10% threshold.",
    options: [
      { letter: "A", label: "1" },
      { letter: "B", label: "2" },
      { letter: "C", label: "3\u20134" },
      { letter: "D", label: "5\u20137" },
      { letter: "E", label: "8 or more" },
    ],
  },
  {
    id: "q4",
    number: 4,
    title: "Forward Revenue Visibility",
    prompt:
      "How many months of income are contractually committed or scheduled under signed or enforceable agreement as of today?",
    definition:
      "Only income secured by enforceable agreement qualifies.",
    options: [
      { letter: "A", label: "Less than 1 month" },
      { letter: "B", label: "1\u20132 months" },
      { letter: "C", label: "3\u20135 months" },
      { letter: "D", label: "6\u201311 months" },
      { letter: "E", label: "12 or more months" },
    ],
  },
  {
    id: "q5",
    number: 5,
    title: "Earnings Variability",
    prompt:
      "Over the last 12 months, what was the largest percentage difference between your highest and lowest monthly income, measured relative to your average monthly income?",
    definition:
      "Calculation anchor: Difference \u00f7 average monthly income.",
    options: [
      { letter: "A", label: "More than 75%" },
      { letter: "B", label: "50\u201375%" },
      { letter: "C", label: "25\u201349%" },
      { letter: "D", label: "10\u201324%" },
      { letter: "E", label: "Less than 10%" },
    ],
  },
  {
    id: "q6",
    number: 6,
    title: "Income Continuity Without Active Labor",
    prompt:
      "If active labor stopped for 90 consecutive days, what percentage of income would continue without new work performed during that period?",
    definition:
      '\u201cWithout new work\u201d means no client acquisition, servicing, or operational effort during that period.',
    options: [
      { letter: "A", label: "0%" },
      { letter: "B", label: "1\u201325%" },
      { letter: "C", label: "26\u201350%" },
      { letter: "D", label: "51\u201375%" },
      { letter: "E", label: "76\u2013100%" },
    ],
  },
];

export default function DiagnosticPage() {
  const router = useRouter();
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [attested, setAttested] = useState(false);
  const [profile, setProfile] = useState<Record<string, string> | null>(null);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const stored = localStorage.getItem("runpayway_profile");
      if (stored) {
        setProfile(JSON.parse(stored));
      }
    }
  }, []);

  const allAnswered = questions.every((q) => answers[q.id]);
  const canSubmit = allAnswered && attested;

  const handleSubmit = () => {
    if (!canSubmit) return;
    if (typeof window !== "undefined") {
      localStorage.setItem("runpayway_diagnostic", JSON.stringify(answers));
    }
    router.push("/review");
  };

  return (
    <div className="mx-auto max-w-[1280px] px-10">
      {/* Diagnostic Header Block */}
      <section className="max-w-[720px] py-24">
        <h1 className="text-[28px]">Income Stability Score&trade;</h1>
        <p className="mt-2 text-sm text-secondary">Model RP-1.0 | Version 1.0</p>
        <div className="mt-6 space-y-3 text-secondary text-sm">
          <p>
            Complete the assessment using the response options provided for each
            question.
          </p>
          <p>
            All responses must reflect the structural characteristics of income
            at the time of assessment.
          </p>
          <p>
            No explanatory scoring information appears during the assessment.
          </p>
        </div>
      </section>

      <Divider />

      {/* Profile Summary Block */}
      <section className="max-w-[720px] mb-12">
        <p className="text-sm font-medium text-navy mb-3">Income Structure Profile</p>
        <div className="text-sm text-secondary space-y-1">
          <p>
            Assessment Title:{" "}
            <span className="text-navy">
              {profile?.assessmentTitle || "\u2014"}
            </span>
          </p>
          <p>
            Email:{" "}
            <span className="text-navy">{profile?.email || "\u2014"}</span>
          </p>
          <p>
            Country / Region:{" "}
            <span className="text-navy">\u2014</span>
          </p>
          <p>
            Primary Income Role:{" "}
            <span className="text-navy">
              {profile?.primaryIncomeModel || "\u2014"}
            </span>
          </p>
        </div>
      </section>

      <Divider />

      {/* Question Set */}
      <section className="max-w-[720px]">
        {questions.map((q, idx) => (
          <div key={q.id}>
            {idx > 0 && <hr className="border-divider my-12" />}
            <div>
              <p className="text-sm font-semibold text-navy mb-1">
                Q{q.number} &mdash; {q.title}
              </p>
              <p className="font-semibold text-navy text-base mt-2">
                {q.prompt}
              </p>
              <div className="mt-4 space-y-2">
                {q.options.map((opt) => (
                  <label
                    key={opt.letter}
                    className={`flex items-center gap-3 px-4 py-3 rounded-md border cursor-pointer text-sm transition-colors ${
                      answers[q.id] === opt.letter
                        ? "border-navy bg-navy/5 text-navy font-medium"
                        : "border-divider text-secondary hover:border-navy/30"
                    }`}
                  >
                    <input
                      type="radio"
                      name={q.id}
                      value={opt.letter}
                      checked={answers[q.id] === opt.letter}
                      onChange={() =>
                        setAnswers((prev) => ({ ...prev, [q.id]: opt.letter }))
                      }
                      className="h-4 w-4 accent-navy"
                    />
                    <span>
                      {opt.letter}. {opt.label}
                    </span>
                  </label>
                ))}
              </div>
              <p className="mt-3 text-xs text-secondary italic">
                {q.definition}
              </p>
            </div>
          </div>
        ))}
      </section>

      <Divider />

      {/* Attestation Statement */}
      <section className="max-w-[720px]">
        <p className="text-sm text-secondary mb-4">
          I confirm that my responses reflect the structural characteristics of
          income to the best of my knowledge at the time of assessment.
        </p>
        <label className="flex items-start gap-3 cursor-pointer">
          <input
            type="checkbox"
            checked={attested}
            onChange={(e) => setAttested(e.target.checked)}
            className="mt-1 h-4 w-4 rounded border-divider"
          />
          <span className="text-sm text-secondary">
            I confirm the information above is accurate to the best of my
            knowledge.
          </span>
        </label>
      </section>

      {/* Navigation Controls */}
      <section className="max-w-[720px] flex items-center gap-4 mt-12 pb-24">
        <Link
          href="/welcome"
          className="text-sm text-secondary hover:text-navy font-medium"
        >
          Back to Profile
        </Link>
        <button
          onClick={handleSubmit}
          disabled={!canSubmit}
          className={`bg-navy text-white px-6 py-3 rounded-md text-sm font-medium ${
            canSubmit ? "hover:opacity-90" : "opacity-50 cursor-not-allowed"
          }`}
        >
          Review Responses
        </button>
      </section>
    </div>
  );
}
