export const STANDARD_NAV = [
  { label: "Structural Overview", href: "/standard" },
  { label: "Measurement Philosophy", href: "/standard/philosophy" },
  { label: "Standards Adoption", href: "/standard/adoption" },
  { label: "Measurement Architecture", href: "/standard/architecture" },
  { label: "Definitions", href: "/standard/definitions" },
  { label: "Payway Rating\u2122", href: "/standard/rating" },
  { label: "Rating Bands", href: "/standard/bands" },
  { label: "Revenue Composition", href: "/standard/composition" },
  { label: "Pressure Sensitivity", href: "/standard/pressure" },
  { label: "Structural Variables", href: "/standard/variables" },
  { label: "Reassessment", href: "/standard/reassess" },
  { label: "Governance", href: "/standard/governance" },
  { label: "Disclosure", href: "/standard/disclosure" },
] as const;
